---
title: "Non-human primiate oral sample cumulative decay curves from Kraken2 GTDB r202 database"
author: "Irina Velsko"
date: "`r format(Sys.time(), '%b %d, %Y')`"
output: github_document
---

```{r load_libraries, echo = F, message = F}
library(knitr)
library(janitor)
library(cuperdec)
library(data.table)
library(magrittr) ## for pipes!
library(dplyr) # for mutate()!
library(tidyverse)
```

Set the working directory of the notebook to the parent directory of the 
notebook itself.  

```{r setup}
knitr::opts_knit$set(root.dir = normalizePath(".."))
```

Load metadata
```{r load_metadata}
# get only primate_oral calculus and sources from the metadata table
lib_metadata <- fread("./00-documentation/strep_clades_metadata.tsv") %>%
  filter(str_detect(Study, "Asangba2022|Ozga2019|Ottoni2019|FellowsYates2021|Brealey2020|Moraitou2022|HMP2012|Oh2016|Rampelli|Obregon|Slon|Sankaranarayanan|HMP2012|Brito") | str_detect(Sample_alias, "JAE|VLC")) %>%
  distinct()

# list Brito samples to remove them
brito <- lib_metadata %>%
  filter(Study == "Brito2016") %>%
  select(Secondary_sample_accession) %>%
  unique() %>%
  pull()

```


Read in the primate_oral calculus tables.
```{r load_data}
# read in the species table
primate_oral_raw <- fread("./05-results/baboon_calc.kraken2.gtdb.report_mpa.tsv") %>%
  full_join(., fread("./05-results/gorilla_calc.kraken2.gtdb.report_mpa.tsv"), by = "#Classification") %>%
  full_join(., fread("./05-results/howler_calc.kraken2.gtdb.report_mpa.tsv"), by = "#Classification") %>%
  full_join(., fread("./05-results/nhp_os.kraken2.gtdb.report_mpa.tsv"), by = "#Classification") %>%
  full_join(., fread("./05-results/mod_calc.kraken2.gtdb.report_mpa.tsv"), by = "#Classification") %>%
  full_join(., fread("./05-results/ind_buccal_mucosa.kraken2.gtdb.report_mpa.tsv"), by = "#Classification") %>%
  full_join(., fread("./05-results/ind_saliva.kraken2.gtdb.report_mpa.tsv"), by = "#Classification") %>%
  replace(is.na(.), 0)

# read in the file names to add as column headers
primate_names <- fread("./05-results/baboon_names.tsv", header = F) %>%
  bind_rows(., fread("./05-results/gorilla_names.tsv", header = F)) %>%
  bind_rows(., fread("./05-results/howler_names.tsv", header = F)) %>%
  bind_rows(., fread("./05-results/nhp_os_names.tsv", header = F)) %>%
  bind_rows(., fread("./05-results/mod_calc_names.tsv", header = F)) %>%
  bind_rows(., fread("./05-results/indbm_names.tsv", header = F)) %>%
  bind_rows(., fread("./05-results/indsal_names.tsv", header = F)) %>%
  pull()

# add the sample names to the table
# move the lineage to the rownames so only samples are left as columns
primate_oral_raw <- primate_oral_raw %>%
  column_to_rownames("#Classification")

# add the sample names
colnames(primate_oral_raw) <- primate_names

# move the lineage back to a column
primate_oral_raw <- primate_oral_raw %>%
  rownames_to_column("Lineage")

# now add the chimpanzees
primate_oral_raw <- primate_oral_raw %>%
  full_join(., fread("./05-results/chimp_calc.kraken2.gtdb.report_mpa.tsv") %>%
            rename(Lineage = 1), by = "Lineage") %>%
  replace(is.na(.), 0)

# filter to have only species and remove all species with <1000 reads assigned
# even filtering out taxa with <10000 counts doesn't help
primate_oral_sp <- primate_oral_raw %>% 
  # remove Brito samples
  select(-matches(brito %>% str_c(collapse = "|"))) %>%
  # and remove blanks
  select(-matches("BK1|BK2|BK3|BK4")) %>%
  filter(str_detect(Lineage, "s__s__")) %>%
  separate(Lineage, into = c("domain","phylum","class","order","family","genus","species"), sep = "\\|", extra = "merge") %>%
  select(-c("domain","phylum","class","order","family","genus")) %>%
  mutate(species = str_replace_all(species, "s__s__","")) %>%
  adorn_totals(where = "col") %>%
  filter(Total > 1000) %>%
  select(-Total) %>%
  arrange(species)

# and get all the samples in the final table
primate_names_full <- primate_oral_sp %>%
  slice_head(n = 1) %>%
  pivot_longer(!species, names_to = "Library_ID", values_to = "Counts") %>%
  select(Library_ID) %>%
  unique() %>%
  pull()

```


```{r set_database}
# load the database and convert to a tibble, then clean up dupliate entries
source_table <- fread("./00-documentation/cuperdec_oral_sources_gtdb_r202.tsv") %>%
  select(species, Isolation_Source) %>%
  as_tibble() %>%
  # remove duplicates
  distinct()
  # if there are 2 entries then the species has both an "oral" source and an "other" source
  # this is b/c at least 1 genome has the isolation source nonindicated as "oral" in NCBI
  # since at least 1 genome was isolated from an "oral" site, we can say it's oral
  # and need to remove the row that has the source as "other"
source_table <- source_table %>%
  anti_join(source_table %>%
            select(species, Isolation_Source) %>% 
            group_by(species) %>% 
            count() %>% 
            filter(n > 1) %>% 
            select(species) %>% ungroup()) %>%
  # and then add back those species with an isolation source of "oral"
  bind_rows(., source_table %>%
            select(species, Isolation_Source)%>% 
            group_by(species) %>% 
            count() %>% 
            filter(n > 1) %>% 
            select(species) %>% 
            ungroup() %>%
            mutate(Isolation_Source = "oral"))


database <- load_database(source_table, target = "oral") %>% print()

```


```{r taxatable}

tax_table <- primate_oral_sp %>%
  # full_join(., source_sp) %>%
  # need to convert NA to 0
  mutate_all(~replace(., is.na(.), 0))

taxatable <- load_taxa_table(tax_table) # %>% print()

```

```{r metamap}
metadata <- lib_metadata  %>%
  # now make the names match what was used in eager and the species tables now have
  mutate(Run_accession = ifelse(Sample_type == "calculus" & Sample_group == "non_human_primate", Sample_alias, Run_accession),
         Run_accession = ifelse(str_detect(Sample_alias, "JAE|VLC"), Sample_alias, Run_accession),
         Run_accession = ifelse(Study == "Moraitou2022", Secondary_sample_accession, Run_accession),
         Run_accession = ifelse(Study == "HMP2012", Secondary_sample_accession, Run_accession),
         Run_accession = ifelse(Study == "Ozga2019", Sample_alias, Run_accession)) %>%
  # select only the samples of interest and the sources
  right_join(., primate_names_full %>% as_data_frame(.) %>% rename(Run_accession = 1) %>%
               filter(!str_detect(Run_accession, brito %>% str_c(collapse = "|")))) %>%
  # remove blanks
  filter(!str_detect(Run_accession, "BK1|BK2|BK3|BK4")) %>%
  select(Run_accession, Sample_type, Host) %>%
  distinct() %>%
  unite(Sample_type, Host, Sample_type, sep = " ") %>%
  mutate(Sample_type = str_replace_all(Sample_type, "oral_swab",""),
         Sample_type = str_replace_all(Sample_type, "buccal_","buccal ")) %>%
  mutate(Sample_type = fct_relevel(Sample_type, "Human saliva","Human buccal mucosa","Human calculus","Chimpanzee calculus","Baboon calculus","Gorilla calculus","Howler monkey calculus"))


metadata_map <- load_map(metadata,
                     sample_col = "Run_accession",
                     source_col = "Sample_type") # %>% print()

metadata_map %>%
  distinct() %>%
  group_by(Sample_Source) %>%
  count()%>%
  ungroup()

```

```{r}

# in metadata_map but not taxatable
taxatable %>% select(Sample) %>% unique() %>%
  anti_join(., metadata_map) %>%
  arrange(Sample)

# in taxatable but not metadata_map
metadata_map %>%
  anti_join(., taxatable %>% select(Sample) %>% unique())

```



```{r simple_curve}
curves <- calculate_curve(taxatable, database = database) %>%
  print()

plot_cuperdec(curves)



curves %>%
  group_by(Sample) %>%
  slice_min(Rank, n = 20) %>%
  left_join(., source_table %>%
              rename(Taxon = species), by = "Taxon")

```


```{r metadata_curve}
plot_cuperdec(curves, metadata_map, restrict_x = 250)

```

```{r adaptive_rank_burnin}

adaptive_rank_burnin_result <- adaptive_burnin_filter(curves, percent_threshold = 25) 
cd_curve_plot <- plot_cuperdec(curves, metadata_map, adaptive_rank_burnin_result, restrict_x = 250)
cd_curve_plot


# ggsave("./06-publication/supplemental_figures/Sup_fig_S4/cuperdec_non_human_primates.png", plot = cd_curve_plot, device = "png",
#        scale = 1, width = 7, height = 5, units = c("in"), dpi = 300)
# 
# ggsave("./06-publication/supplemental_figures/Sup_fig_S4/cuperdec_non_human_primates.pdf", plot = cd_curve_plot, device = "pdf",
#        scale = 1, width = 7, height = 5, units = c("in"), dpi = 300)

```

```{r discard_list, eval = F}
# poorly-preserved samples
discard_list <- adaptive_rank_burnin_result %>% filter(!Passed) %>%
  # select only the samples, not the source controls
  # filter(str_detect(Sample, "BB")) %>% 
  select(Sample)
discard_list

fwrite(discard_list, "./05-results/cuperdec_primate_oral_poor_samples.tsv", sep = "\t", quote = F)

```



