---
title: "Mapping results for S. sinensis and S. sanguinis in CMC samples"
author: "Irina Velsko"
date: "`r format(Sys.time(), '%b %d, %Y')`"
output:
    github_document:
        fig_width: 8
        fig_height: 6
        toc: true
---

```{r load_libraries, echo = F, message = F}
library(knitr)
library(data.table)
library(janitor)
library(dtplyr)
library(tidyverse)
library(patchwork)
opts_chunk$set(echo=F, warning=F, message=F, dpi=150)
```

Set the working directory of the notebook to the parent directory of the 
notebook itself.  

```{r setup}
knitr::opts_knit$set(root.dir = normalizePath(".."))
```

```{r}
sp_colors <- c("sanguinis" = "#BDD7C1", "sanguinis_A" = "#87CCBB", 
               "sanguinis_C" = "#51C1B5", "sanguinis_D" = "#1BB6AF", 
               "sanguinis_E" = "#14A6B2", "sanguinis_F" = "#0D96B4", 
               "sanguinis_G" = "#0686B8", "sanguinis_H" = "#0076BB", 
               "sanguinis_I" = "#0562A6", "sinensis" = "#FC6882")

sp_colors <- c("sanguinis" = "#ffffd9", "sanguinis_A" = "#edf8b1", "sanguinis_C" = "#c7e9b4", "sanguinis_D" = "#7fcdbb", "sanguinis_E" = "#41b6c4", "sanguinis_F" = "#1d91c0", "sanguinis_G" = "#225ea8", "sanguinis_H" = "#253494", "sanguinis_I" = "#081d58", "sinensis" = "#C70E7B")
```


```{r load_metadata}

genome_metadata <- fread("./00-documentation/sinensis_sanguinis_contigs.tsv") %>%
  as_tibble()

# also need to normalize the number of SNPs by number of bps in each genome
genome_lengths <- fread("./00-documentation/S_sinensis_sanguinis.fna.fai", sep = "\t", header = FALSE) %>%
  as_tibble() %>%
  rename(Contig = 1,
         Length = 2,
         TotalLen = 3,
         Offset = 4,
         Offset_1 = 5) %>%
  full_join(., genome_metadata %>%
              select(Contig, Assembly_accession), by = "Contig") %>%
  group_by(Assembly_accession) %>%
  summarize(GenomeLen = sum(Length)) %>%
  ungroup()

sp_order <- genome_lengths %>%
  left_join(., genome_metadata, by = "Assembly_accession") %>%
  select(Assembly_accession, GTDB_species) %>%
  distinct() %>%
  arrange(GTDB_species) %>%
  pull(Assembly_accession)


#  
lib_metadata <- fread("./00-documentation/strep_clades_metadata.tsv") %>%
  as_tibble() %>%
  filter(!str_detect(Study, "ObregonTito2015|Oh2016|Rampelli2015|Sankaranarayanan2015|Slon2017")) %>%
    filter(Sample_group != "non_human_primate",
           !str_detect(Sample_group,"urban_gut|blank|Bone")
           ) %>%
  mutate(Secondary_sample_accession = ifelse(Study == "Velsko2018", Sample_alias,Secondary_sample_accession),
         Secondary_sample_accession = ifelse(Study == "Velsko2023", Sample_alias,Secondary_sample_accession),
         Secondary_sample_accession = ifelse(Study == "Velsko2022", Sample_alias,Secondary_sample_accession),
         Secondary_sample_accession = ifelse(Study == "FellowsYates2021", Sample_alias,Secondary_sample_accession),
         Secondary_sample_accession = ifelse(Study == "Clemente2015", Run_accession,Secondary_sample_accession),
         Secondary_sample_accession = ifelse(Study == "Lassalle2017", Run_accession,Secondary_sample_accession),
         Secondary_sample_accession = ifelse(Study == "Brealey2020", Sample_alias,Secondary_sample_accession),
         Secondary_sample_accession = ifelse(Study == "Eerkens2018", Run_accession,Secondary_sample_accession),
         Secondary_sample_accession = ifelse(Study == "Eisenhofer2020", Run_accession,Secondary_sample_accession),
         Secondary_sample_accession = ifelse(Study == "Fagernaes2022", Sample_alias,Secondary_sample_accession),
         Secondary_sample_accession = ifelse(Study == "Granehaell2021", Sample_alias,Secondary_sample_accession),
         Secondary_sample_accession = ifelse(Study == "Jacobson2020", Sample_alias,Secondary_sample_accession),
         Secondary_sample_accession = ifelse(Study == "Mann2018", Sample_alias,Secondary_sample_accession),
         Secondary_sample_accession = ifelse(Study == "Mann2018_w", Run_accession,Secondary_sample_accession),
         Secondary_sample_accession = ifelse(Study == "Ottoni2019", Sample_alias,Secondary_sample_accession),
         Secondary_sample_accession = ifelse(Study == "Ottoni2021", Run_accession,Secondary_sample_accession),
         Secondary_sample_accession = ifelse(Study == "Ozga2019", Sample_alias,Secondary_sample_accession),
         Secondary_sample_accession = ifelse(Study == "Ottoni2021", Run_accession,Secondary_sample_accession),
         Secondary_sample_accession = ifelse(Study == "Iberian", Sample_alias,Secondary_sample_accession),
         Secondary_sample_accession = ifelse(Study == "Pacific", Sample_alias,Secondary_sample_accession),
         Secondary_sample_accession = ifelse(Study == "Weyrich2017", Run_accession,Secondary_sample_accession),
         Secondary_sample_accession = ifelse(Study == "Warinner2014", Sample_alias,Secondary_sample_accession),
         Secondary_sample_accession = ifelse(Study == "Neukamm2020", Sample_alias,Secondary_sample_accession)) %>%
  mutate(Secondary_sample_accession = str_replace_all(Secondary_sample_accession, ".SG1.1",""))

# also read in cmc metadata for plots later
cmc_metadata <- fread("https://raw.githubusercontent.com/ivelsko/Cameroon_plaque/master/00-documentation.backup/01-cameroon_hunter_gatherer_metadata.tsv") %>%
  as_tibble() %>%
  rename(Library_ID = 1) %>%
  filter(Env == "CMC") %>%
  select(Library_ID, Ethnic_Group, Market_integration, Sex, Tooth_site)

```

```{r}
# file with species names and clade designations
gtdb_clades <- fread("./00-documentation/dRep_gtdb_clades.tsv") %>%
  as_tibble()

gtdb_clades <- gtdb_clades %>%
  mutate(Clade = fct_relevel(Clade, "Sanguinis","Mitis","Salivarius","Anginosus","Bovis","Pyogenic","Mutans","Downei","Other","Unknown"))

```


## CMC

```{r load_data}
# read in poor samples determined by cuperdec
poor_samples <- fread("./05-results/cuperdec_ind_sal_poor_samples.tsv") %>%
  pull(Sample)

# read in the species table
mod_oral_raw <- fread("./05-results/mod_calc.kraken2.gtdb.report_mpa.tsv") %>%
  full_join(., fread("./05-results/ind_plaque.kraken2.gtdb.report_mpa.tsv"), by = "#Classification") %>%
  full_join(., fread("./05-results/ind_buccal_mucosa.kraken2.gtdb.report_mpa.tsv"), by = "#Classification") %>%
  full_join(., fread("./05-results/ind_saliva.kraken2.gtdb.report_mpa.tsv"), by = "#Classification") %>%
  full_join(., fread("./05-results/nonind_plaque.kraken2.gtdb.report_mpa.tsv"), by = "#Classification") %>%
  full_join(., fread("./05-results/nonind_buccal_mucosa.kraken2.gtdb.report_mpa.tsv"), by = "#Classification") %>%
  full_join(., fread("./05-results/nonind_saliva.kraken2.gtdb.report_mpa.tsv"), by = "#Classification") %>%
  replace(is.na(.), 0)

# read in the file names to add as column headers
mod_names <- fread("./05-results/mod_calc_names.tsv", header = F) %>%
  bind_rows(., fread("./05-results/indpq_names.tsv", header = F)) %>%
  bind_rows(., fread("./05-results/indbm_names.tsv", header = F)) %>%
  bind_rows(., fread("./05-results/indsal_names.tsv", header = F)) %>%
  bind_rows(., fread("./05-results/nonindpq_names.tsv", header = F)) %>%
  bind_rows(., fread("./05-results/nonindbm_names.tsv", header = F)) %>%
  bind_rows(., fread("./05-results/nonindsal_names.tsv", header = F)) %>%
  pull()

# add the sample names to the table
# move the lineage to the rownames so only samples are left as columns
mod_oral_raw <- mod_oral_raw %>%
  as_tibble() %>%
  column_to_rownames("#Classification")

# add the sample names
colnames(mod_oral_raw) <- mod_names

# move the lineage back to a column
mod_oral_raw <- mod_oral_raw %>%
  rownames_to_column("Lineage")

# filter to have only Streptococcus species
mod_oral_raw_sp <- mod_oral_raw %>% 
  filter(str_detect(Lineage, "s__s__")) %>%
  separate(Lineage, into = c("domain","phylum","class","order","family","genus","Species"), sep = "\\|", extra = "merge") %>%
  select(-c("domain","phylum","class","order","family","genus")) %>%
  mutate(Species = str_replace_all(Species, "s__s__","")) %>%
  filter(str_detect(Species, "Streptococcus"))

```

```{r}
# which samples have which strep species as the most abundant?
mod_oral_raw_sp %>%
  pivot_longer(!Species, names_to = "Library_ID", values_to = "Counts") %>%
  left_join(., gtdb_clades, by = "Species") %>%
  filter(str_detect(Clade, "Sanguinis"),
         str_detect(Library_ID, "CMC")) %>%
  group_by(Library_ID) %>%
  slice_max(Counts) %>%
  ungroup() %>%
  arrange(Species) %>%
  group_by(Species) %>%
  count()

cmc_most_abund_strep <- mod_oral_raw_sp %>%
  pivot_longer(!Species, names_to = "Library_ID", values_to = "Counts") %>%
  left_join(., gtdb_clades, by = "Species") %>%
  filter(str_detect(Clade, "Sanguinis"),
         str_detect(Library_ID, "CMC")) %>%
  group_by(Library_ID) %>%
  slice_max(Counts) %>%
  ungroup() %>%
  select(-Counts, -Clade) %>%
  mutate(Species = str_replace_all(Species, "Streptococcus ", ""))

```


Load in the coverage information per bam file for the CMC samples and put it
together into a large data frame
```{r cmc_load_cov, eval = F}

sss_list_cmc <- list.files(path = "./04-analysis/sinensis_sanguinis_mapping/non_ind_plaque", pattern = ".cov", full.names = T)

sss_cmc_cov <- map_dfr(sss_list_cmc, function(fn) {
  fread(fn, col.names = c("Contig", "Depth", "Breadth","Genome_length","Proportion_covered"), sep = "\t") %>%
  mutate(Library_ID = basename(fn)) %>%
  as_tibble()
}) %>%
  arrange(Library_ID) %>%
# now add the genome accession to the table for filtering
# remove the end of the file name from the Library_ID
  mutate(Library_ID = str_replace_all(Library_ID, "-sinensis_sanguinis_rep.mapped_rmdup.cov","")) 

  fwrite(sss_cmc_cov, "./05-results/sss_cmc_cov.tsv", quote = F, sep = "\t")

```
  
```{r}

sss_cmc_cov <- fread("./05-results/sss_cmc_cov.tsv.gz") %>%
  as_tibble()

sss_cmc_cov <- sss_cmc_cov %>%
  full_join(., genome_metadata, by = "Contig") %>%
  select(Assembly_accession, everything())
 
```


```{r cmc_genome_coverages}

Genomes <- genome_metadata %>%
  select(Assembly_accession) %>%
  unique() %>%
  pull()


cmc_genomes_coverage <- sss_cmc_cov %>%
  filter(Assembly_accession != "all") %>%
  filter(Depth > 0) %>%
  group_by(Library_ID, Assembly_accession) %>%
  summarize(bases_cov_min1X = sum(Breadth)) %>%
  ungroup() %>%
  full_join(., sss_cmc_cov %>%
              filter(Assembly_accession != "all") %>%
               select(Assembly_accession, Library_ID, Depth, Breadth) %>%
               filter(Depth >= 2) %>%
               group_by(Library_ID, Assembly_accession) %>%
               summarize(bases_cov_min2X = sum(Breadth)) %>%
               ungroup()) %>%
  full_join(., sss_cmc_cov %>%
              filter(Assembly_accession != "all") %>%
               select(Assembly_accession, Library_ID, Depth, Breadth) %>%
               filter(Depth >= 5) %>%
               group_by(Library_ID, Assembly_accession) %>%
               summarize(bases_cov_min5X = sum(Breadth)) %>%
               ungroup()) %>%
  full_join(., genome_lengths, by = "Assembly_accession") %>%
  group_by(Library_ID, Assembly_accession) %>%
  summarize(breadth_1X = bases_cov_min1X / GenomeLen * 100,
            breadth_2X = bases_cov_min2X / GenomeLen * 100,
            breadth_5X = bases_cov_min5X / GenomeLen * 100) %>%
  ungroup()

```

```{r cmc_coverages}
# species with max breadth of coverage at 1X depth
cmc_genomes_coverage %>%
  select(Library_ID, Assembly_accession, breadth_1X) %>%
  group_by(Library_ID) %>%
  slice_max(breadth_1X) %>%
  left_join(., genome_metadata %>%
              select(Assembly_accession, GTDB_species)) %>%
  distinct() %>%
  left_join(., cmc_most_abund_strep, by = "Library_ID") %>%
  mutate(same_sp = GTDB_species == Species) %>%
  arrange(desc(same_sp), GTDB_species) %>%
  filter(Species == "sinensis")
  
# species with max breadth of coverage at 2X depth
cmc_genomes_coverage %>%
  select(Library_ID, Assembly_accession, breadth_2X) %>%
  group_by(Library_ID) %>%
  slice_max(breadth_2X) %>%
  left_join(., genome_metadata %>%
              select(Assembly_accession, GTDB_species)) %>%
  distinct() %>%
  left_join(., cmc_most_abund_strep, by = "Library_ID") %>%
  mutate(same_sp = GTDB_species == Species) %>%
  arrange(desc(same_sp), GTDB_species) %>%
  # remove CMC032.B b/c it has no coverage at 2X depth (poor sample)
  filter(Library_ID != "CMC032.B0101") %>%
  filter(Species == "sinensis")

# species with max breadth of coverage at 5X depth
cmc_genomes_coverage %>%
  select(Library_ID, Assembly_accession, breadth_5X) %>%
  group_by(Library_ID) %>%
  slice_max(breadth_5X) %>%
  left_join(., genome_metadata %>%
              select(Assembly_accession, GTDB_species)) %>%
  distinct() %>%
  left_join(., cmc_most_abund_strep, by = "Library_ID") %>%
  mutate(same_sp = GTDB_species == Species) %>%
  arrange(desc(same_sp), GTDB_species) %>%
  # remove CMC032.B b/c it has no coverage at 5X depth (poor sample)
  filter(Library_ID != "CMC032.B0101") %>%
  filter(Species == "sinensis")
 
```


```{r}
cmc_genomes_coverage_plot <-  cmc_genomes_coverage %>%
  pivot_longer(!Library_ID:Assembly_accession, names_to = "Depth", values_to = "Breadth") %>%
  filter(Depth != "breadth_2X") %>%
  left_join(., genome_metadata %>%
              select(Assembly_accession, GTDB_species)) %>%
  distinct() %>%
  full_join(., cmc_most_abund_strep %>%
               separate(Species, into = "species", sep = "_", extra = "drop"), by = "Library_ID") %>%
  filter(str_detect(species, "sinensis|sanguinis")) %>%
  mutate(Assembly_accession = fct_relevel(Assembly_accession, sp_order)) %>%
  ggplot(., aes(x = Assembly_accession, y = Breadth, fill = GTDB_species)) + # Species
         geom_boxplot(outlier.colour = NA) +
         geom_jitter(aes(shape = species), alpha = 0.5, width = 0.2) +
         scale_fill_manual(values = sp_colors) +
         scale_shape_manual(values = c(4, 1)) +
         # scale_shape_manual(values = c(8, 3, 6, 1)) +
         theme_minimal(base_size = 10) +
         theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)) +
         ylim(0,100) +
         ylab("Breadth of genome covered at least 1X (%)") +
         xlab("Assembly accession") +
  facet_wrap(~Depth)
cmc_genomes_coverage_plot

# ggsave("./06-publication/supplemental_figures/Sup_fig_S17/cmc_genomes_coverage_plot.pdf", plot = cmc_genomes_coverage_plot, device = "pdf",
#        scale = 1, width = 8, height = 5, units = c("in"), dpi = 300)


```


```{r}
# list the samples that have >10% of the genome covered 2X in the sanguinis and sinensis genomes with the highest coverage
# GCF_003943655.1 and GCF_000767835.1
cmc_over_10 <- cmc_genomes_coverage %>%
  pivot_longer(!Library_ID:Assembly_accession, names_to = "Depth", values_to = "Breadth") %>%
  filter(Depth == "breadth_5X",
         str_detect(Assembly_accession, "GCF_013343115.1|GCF_000767835.1"),
         Breadth >= 10) %>%
  select(Library_ID) %>%
  distinct() %>%
  pull(Library_ID)

```


```{r cov_all_together}

cmc_genomes_coverage %>%
  pivot_longer(!Library_ID:Assembly_accession, names_to = "Depth", values_to = "Breadth") %>%
  mutate(Library_ID = str_replace_all(Library_ID, ".SG1","")) %>%
  filter(Depth == "breadth_1X") %>%
  left_join(., genome_metadata %>%
              select(Assembly_accession, GTDB_species) %>%
              rename(Assembly_species = GTDB_species)) %>%
  distinct() %>%
  full_join(., cmc_most_abund_strep %>%
               separate(Species, into = "species", sep = "_", extra = "drop"), by = "Library_ID") %>%
  filter(str_detect(species, "sinensis|sanguinis")) %>%
  drop_na(Breadth) %>%
  # get rid of the species cluster info so have only sanguinis/sinensis for plotting
  separate(Assembly_species, into = "Assembly_species", sep = "_", extra = "drop") %>%
  filter(Library_ID != "CMC032.B0101") %>%
  group_by(Library_ID, Assembly_species) %>%
  slice_max(Breadth, n = 1) %>%
  ungroup() %>%
  ggplot(.) +
         geom_point(aes(x = Assembly_species, y = Breadth, fill = species), shape = 21, color = "black") + # , fill = "#766df8"
         geom_line(aes(x = Assembly_species, y = Breadth, group = Library_ID), linetype="dotted") +
         theme_minimal(base_size = 12) +
         scale_fill_manual(values = sp_colors) +
         theme(axis.text.x = element_text(angle = 0, hjust = 0.5, size = 12),
               axis.text.y = element_text(size = 12)) +
         xlab("Genome") +
         ylab("% of genome covered at 1X") +
         facet_wrap(~species)


cmc_genomes_coverage %>%
  pivot_longer(!Library_ID:Assembly_accession, names_to = "Depth", values_to = "Breadth") %>%
  mutate(Library_ID = str_replace_all(Library_ID, ".SG1","")) %>%
  filter(Depth == "breadth_1X") %>%
  left_join(., genome_metadata %>%
              select(Assembly_accession, GTDB_species) %>%
              rename(Assembly_species = GTDB_species)) %>%
  distinct() %>%
  full_join(., cmc_most_abund_strep %>%
               separate(Species, into = "species", sep = "_", extra = "drop"), by = "Library_ID") %>%
  filter(str_detect(species, "sinensis|sanguinis")) %>%
  drop_na(Breadth) %>%
  # get rid of the species cluster info so have only sanguinis/sinensis for plotting
  separate(Assembly_species, into = "Assembly_species", sep = "_", extra = "drop") %>%
  filter(Library_ID != "CMC032.B0101") %>%
  group_by(Library_ID, Assembly_species) %>%
  slice_max(Breadth, n = 1) %>%
  ungroup() %>%
  select(-Assembly_accession) %>%
  pivot_wider(names_from = "Assembly_species", values_from = "Breadth") %>%
  mutate(Difference = sanguinis - sinensis,
         Slope = (sinensis - sanguinis) / (1-0)) %>%
  # filter(Slope >= 1 | Slope <= -1) %>%
  ggplot(., aes(x = species, y = Slope, fill = species)) + # Species
         geom_boxplot(outlier.colour = NA) +
         geom_jitter(aes(shape = species), alpha = 0.5, width = 0.2) +
         scale_fill_manual(values = sp_colors) +
         scale_shape_manual(values = c(4, 1)) +
         # scale_shape_manual(values = c(8, 3, 6, 1)) +
         theme_minimal(base_size = 12) +
         theme(axis.text.x = element_text(angle = 0, hjust = 0.5)) +
         geom_hline(yintercept = 0, linetype = "dashed") +
         ylab("Slope") +
         xlab("Species") 


```

```{r cov_all_independent}

cmc_together_cov_plot <- cmc_genomes_coverage %>%
  pivot_longer(!Library_ID:Assembly_accession, names_to = "Depth", values_to = "Breadth") %>%
  mutate(Library_ID = str_replace_all(Library_ID, ".SG1","")) %>%
  filter(Depth == "breadth_1X") %>%
  left_join(., genome_metadata %>%
              select(Assembly_accession, GTDB_species) %>%
              rename(Assembly_species = GTDB_species)) %>%
  distinct() %>%
  filter(str_detect(Assembly_accession, "013343115|000767835")) %>%
  full_join(., cmc_most_abund_strep %>%
               separate(Species, into = "species", sep = "_", extra = "drop"), by = "Library_ID") %>%
  filter(str_detect(species, "sinensis|sanguinis")) %>%
  filter(Library_ID != "CMC032.B0101") %>%
  drop_na(Breadth) %>%
  # get rid of the species cluster info so have only sanguinis/sinensis for plotting
  separate(Assembly_species, into = "Assembly_species", sep = "_", extra = "drop") %>%
  ggplot(.) +
         geom_point(aes(x = Assembly_species, y = Breadth, fill = species), shape = 21, color = "black") + # , fill = "#766df8"
         geom_line(aes(x = Assembly_species, y = Breadth, group = Library_ID), linetype="dotted") +
         theme_minimal(base_size = 12) +
         scale_fill_manual(values = sp_colors) +
         theme(axis.text.x = element_text(angle = 0, hjust = 0.5, size = 12),
               axis.text.y = element_text(size = 12)) +
         xlab("Genome") +
         ylab("% of genome covered at 1X") +
         facet_wrap(~species)
cmc_together_cov_plot

cmc_together_cov_box_plot <- cmc_genomes_coverage %>%
  pivot_longer(!Library_ID:Assembly_accession, names_to = "Depth", values_to = "Breadth") %>%
  mutate(Library_ID = str_replace_all(Library_ID, ".SG1","")) %>%
  filter(Depth == "breadth_1X") %>%
  left_join(., genome_metadata %>%
              select(Assembly_accession, GTDB_species) %>%
              rename(Assembly_species = GTDB_species)) %>%
  distinct() %>%
  filter(str_detect(Assembly_accession, "013343115|000767835")) %>%
  full_join(., cmc_most_abund_strep %>%
               separate(Species, into = "species", sep = "_", extra = "drop"), by = "Library_ID") %>%
  filter(str_detect(species, "sinensis|sanguinis")) %>%
  drop_na(Breadth) %>%
  # get rid of the species cluster info so have only sanguinis/sinensis for plotting
  separate(Assembly_species, into = "Assembly_species", sep = "_", extra = "drop") %>%
  select(-Assembly_accession) %>%
  filter(Library_ID != "CMC032.B0101") %>%
  pivot_wider(names_from = "Assembly_species", values_from = "Breadth") %>%
  mutate(Difference = sanguinis - sinensis,
         Slope = (sinensis - sanguinis) / (1-0)) %>%
  # filter(Slope >= 1 | Slope <= -1) %>%
  ggplot(., aes(x = species, y = Slope, fill = species)) + # Species
         geom_boxplot(outlier.colour = NA) +
         geom_jitter(aes(shape = species), alpha = 0.5, width = 0.2) +
         scale_fill_manual(values = sp_colors) +
         scale_shape_manual(values = c(4, 1)) +
         # scale_shape_manual(values = c(8, 3, 6, 1)) +
         theme_minimal(base_size = 12) +
         theme(axis.text.x = element_text(angle = 0, hjust = 0.5, size = 12),
               axis.text.y = element_text(size = 12)) +
         geom_hline(yintercept = 0, linetype = "dashed") +
         ylab("Slope") +
         xlab("Species") 
cmc_together_cov_box_plot

```

```{r}

cmc_ss_together_map <- cmc_together_cov_plot + cmc_together_cov_box_plot +
  plot_layout(widths = c(1.5, 1)) +
  plot_layout(guides = "collect")

cmc_ss_together_map

ggsave("./06-publication/supplemental_figures/Sup_fig_S17/ss_together_map_cmc.pdf", plot = cmc_ss_together_map, device = "pdf",
       scale = 1, width = 8, height = 5, units = c("in"), dpi = 300)

```

### Variants in vcf files
```{r, eval = F}

vcf_list_cmc <- list.files(path = "./04-analysis/sinensis_sanguinis_mapping/non_ind_plaque/", pattern = ".vcf$", full.names = T)

vcf_cmc_snp <- map_dfr(vcf_list_cmc, function(fn) {
  fread(fn, col.names = c("Contig", "POS", "ID","REF","ALT", "QUAL", "FILTER","INFO", "FORMAT","BAM"), sep = "\t", skip = 431) %>%
  mutate(Library_ID = basename(fn)) %>%
  as_tibble() %>%
  filter(FILTER == "PASS")
}) %>%
# remove the end of the file name from the Library_ID
  mutate(Library_ID = str_replace_all(Library_ID, ".sinensis_sanguinis.vcf","")) 

# fwrite(vcf_cmc_snp, "./05-results/ss_vcf_cmc_snp.tsv", quote = F, sep = "\t")

```

```{r}
vcf_cmc_snp <- fread("../strep_clades/05-results/ss_vcf_cmc_snp.tsv.gz") %>%
  as_tibble()

vcf_cmc_sum_snp  <- vcf_cmc_snp %>%
  full_join(., genome_metadata, by = "Contig") %>%
  drop_na(Library_ID) %>%
  group_by(Library_ID, Assembly_accession) %>%
  count() %>%
  ungroup() %>%
  full_join(., genome_metadata %>%
              select(Assembly_accession, Species, GTDB_species), by = "Assembly_accession") %>%
  filter(str_detect(Assembly_accession, "GCF_013343115.1|GCF_000194945.1|GCF_000767835.1|GCF_001578725.1|GCF_019090945.1|GCF_902460385.1")) %>%
  distinct()

vcf_cmc_d2_snp <- vcf_cmc_snp %>%
  full_join(., genome_metadata, by = "Contig") %>%
  drop_na(Library_ID) %>%
  group_by(Library_ID, Assembly_accession) %>%
  distinct() %>%
  ungroup() %>%
  separate(INFO, into = "Depth", extra = "drop", sep = ";") %>%
  mutate(Depth = str_replace_all(Depth, "DP=",""),
         Depth = as.numeric(Depth)) %>% 
  filter(Depth >= 2) %>%
  group_by(Library_ID, Assembly_accession) %>%
  count() %>%
  ungroup() %>%
  full_join(., genome_metadata %>%
              select(Assembly_accession, Species, GTDB_species), by = "Assembly_accession") %>%
  # filter(str_detect(Assembly_accession, "GCF_003943655.1|GCF_003943735.1|GCF_000767835.1|GCF_001578725.1|GCF_019090945.1|GCF_902460385.1")) %>%
  filter(str_detect(Assembly_accession, "GCF_013343115.1|GCF_000194945.1|GCF_000767835.1|GCF_001578725.1|GCF_019090945.1|GCF_902460385.1")) %>%
  distinct()
  

```


```{r}
vcf_cmc_d2_snp %>%
  # filter(str_detect(Library_ID, cmc_over_10 %>% str_c(collapse = "|"))) %>%
  mutate(Assembly_accession = fct_relevel(Assembly_accession, sp_order)) %>%
  full_join(., cmc_most_abund_strep %>%
               filter(Library_ID != "CMC032.B0101") %>%
               separate(Species, into = "species", sep = "_", extra = "drop"), by = "Library_ID") %>%
  filter(str_detect(species, "sinensis|sanguinis")) %>%
  ggplot(., aes(x = Assembly_accession, y = n, fill = GTDB_species)) + # Species
         geom_boxplot(outlier.colour = NA) +
         geom_jitter(aes(shape = species), alpha = 0.5, width = 0.2) +
         scale_fill_manual(values = sp_colors) +
         scale_shape_manual(values = c(4, 1)) +
         # scale_shape_manual(values = c(8, 3, 6, 1)) +
         theme_minimal(base_size = 10) +
         theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
         ylab("Total SNPs/Genome, depth >2") +
         xlab("Assembly accession") 


vcf_cmc_d2_snp %>%
  # filter(str_detect(Library_ID, cmc_over_10 %>% str_c(collapse = "|"))) %>%
  left_join(., genome_lengths) %>%
  mutate(proportion_snps = n / GenomeLen,
         Assembly_accession = fct_relevel(Assembly_accession, sp_order)) %>%
  full_join(., cmc_most_abund_strep %>%
               filter(Library_ID != "CMC032.B0101") %>%
               separate(Species, into = "species", sep = "_", extra = "drop"), by = "Library_ID") %>%
  filter(str_detect(species, "sinensis|sanguinis")) %>%
  arrange(Assembly_accession) %>%
  ggplot(., aes(x = Assembly_accession, y = proportion_snps, fill = GTDB_species)) +
         geom_boxplot(outlier.colour = NA) +
         geom_jitter(aes(shape = species), alpha = 0.5, width = 0.2) +
         scale_fill_manual(values = sp_colors) +
         scale_shape_manual(values = c(4, 1)) +
         # scale_shape_manual(values = c(8, 3, 6, 1)) +
         theme_minimal(base_size = 10) +
         theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
         ylab("% SNPs/Genome, depth >2") +
         xlab("Assembly accession") 


vcf_cmc_sum_snp %>%
  full_join(., cmc_most_abund_strep %>%
               filter(Library_ID != "CMC032.B0101") %>%
               separate(Species, into = "species", sep = "_", extra = "drop"), by = "Library_ID") %>%
  filter(str_detect(species, "sinensis|sanguinis")) %>%
  mutate(Assembly_accession = fct_relevel(Assembly_accession, sp_order)) %>%
  ggplot(., aes(x = Assembly_accession, y = n, fill = GTDB_species)) + # Species
         geom_boxplot(outlier.colour = NA) +
         geom_jitter(aes(shape = species), alpha = 0.5, width = 0.2) +
         scale_fill_manual(values = sp_colors) +
         scale_shape_manual(values = c(4, 1)) +
         # scale_shape_manual(values = c(8, 3, 6, 1)) +
         theme_minimal(base_size = 10) +
         theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
         ylab("Total SNPs/Genome") +
         xlab("Assembly accession") 


vcf_cmc_sum_snp %>%
  left_join(., genome_lengths) %>%
  full_join(., cmc_most_abund_strep %>%
               filter(Library_ID != "CMC032.B0101") %>%
               separate(Species, into = "species", sep = "_", extra = "drop"), by = "Library_ID") %>%
  filter(str_detect(species, "sinensis|sanguinis")) %>%
  mutate(proportion_snps = n / GenomeLen,
         Assembly_accession = fct_relevel(Assembly_accession, sp_order)) %>%
  arrange(Assembly_accession) %>%
  ggplot(., aes(x = Assembly_accession, y = proportion_snps, fill = GTDB_species)) +
         geom_boxplot(outlier.colour = NA) +
         geom_jitter(aes(shape = species), alpha = 0.5, width = 0.2) +
         scale_fill_manual(values = sp_colors) +
         scale_shape_manual(values = c(4, 1)) +
         # scale_shape_manual(values = c(8, 3, 6, 1)) +
         theme_minimal(base_size = 10) +
         theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
         ylab("% SNPs/Genome") +
         xlab("Assembly accession") 


# ./04-analysis/sinensis_sanguinis_mapping/non_ind_plaque/CMC002.A0201.SG1.sinensis_sanguinis.vcf

# maybe make this a alluvial plot with the left side sinensis SNP counts and the right side Sanguinis SNP counts?
# Do samples with higher sanguinis SNP counts have lower sinensis SNP counts?

```

```{r}
vcf_cmc_sum_snp %>%
  left_join(., cmc_metadata, by = "Library_ID") %>%
  left_join(., genome_lengths) %>%
  filter(str_detect(Assembly_accession, "013343115|000767835"),
         Tooth_site == "Anterior") %>%
  mutate(proportion_snps = n / GenomeLen,
         Assembly_accession = fct_relevel(Assembly_accession, "GCF_013343115.1","GCF_000767835.1")) %>%
  mutate(Sample_ID = str_trunc(Library_ID, width = 6, side = "right", ellipsis = "")) %>%
  arrange(Assembly_accession) %>%
  ggplot(.) +
         geom_point(aes(x = Assembly_accession, y = proportion_snps, fill = Tooth_site), shape = 21, color = "black") +
         geom_line(aes(x = Assembly_accession, y = proportion_snps, group = Library_ID), linetype="dotted") +
         scale_fill_manual(values = c("#31D64D", "#FFF800")) +
         theme_minimal(base_size = 8) +
         theme(axis.text.x = element_text(angle = 0, hjust = 0.5, size = 8),
               axis.text.y = element_text(size = 8)) +
         xlab("Genome") +
         ylab("% SNPs/Genome") +
         facet_wrap(~Market_integration)

vcf_cmc_sum_snp %>%
  left_join(., cmc_metadata, by = "Library_ID") %>%
  left_join(., genome_lengths) %>%
  filter(str_detect(Assembly_accession, "013343115|000767835"),
         Tooth_site == "Posterior") %>%
  mutate(proportion_snps = n / GenomeLen,
         Assembly_accession = fct_relevel(Assembly_accession, "GCF_013343115.1","GCF_000767835.1")) %>%
  mutate(Sample_ID = str_trunc(Library_ID, width = 6, side = "right", ellipsis = "")) %>%
  arrange(Assembly_accession) %>%
  ggplot(.) +
         geom_point(aes(x = Assembly_accession, y = proportion_snps, fill = Tooth_site), shape = 21, color = "black") +
         geom_line(aes(x = Assembly_accession, y = proportion_snps, group = Library_ID), linetype="dotted") +
         scale_fill_manual(values = c("#FFF800")) +
         theme_minimal(base_size = 8) +
         theme(axis.text.x = element_text(angle = 0, hjust = 0.5, size = 8),
               axis.text.y = element_text(size = 8)) +
         xlab("Genome") +
         ylab("% SNPs/Genome") +
         facet_wrap(~Market_integration)

```

### Independent mappings

```{r cmc_load_independent_cov, eval = F}
# Sinensis
sinensis_list_cmc <- list.files(path = "./04-analysis/sinensis_sanguinis_mapping/non_ind_plaque/sinensis", pattern = ".rmdup.cov", full.names = T)

sinensis_cmc_cov <- map_dfr(sinensis_list_cmc, function(fn) {
  fread(fn, col.names = c("Contig", "Depth", "Breadth","Genome_length","Proportion_covered"), sep = "\t") %>%
  mutate(Library_ID = basename(fn)) %>%
    as_tibble()
}) %>%
  arrange(Library_ID) %>%
# remove the end of the file name from the Library_ID
  mutate(Library_ID = str_replace_all(Library_ID, "-sinensis.mapped_rmdup.cov",""))

# fwrite(sinensis_cmc_cov, "05-results/sinensis_cmc_indep_cov.tsv", quote = F, sep = "\t")

# Sanguinis
sanguinis_list_cmc <- list.files(path = "./04-analysis/sinensis_sanguinis_mapping/non_ind_plaque/sanguinis", pattern = ".rmdup.cov", full.names = T)

sanguinis_cmc_cov <- map_dfr(sanguinis_list_cmc, function(fn) {
  fread(fn, col.names = c("Contig", "Depth", "Breadth","Genome_length","Proportion_covered"), sep = "\t") %>%
  mutate(Library_ID = basename(fn)) %>%
    as_tibble()
}) %>%
  arrange(Library_ID) %>%
# remove the end of the file name from the Library_ID
  mutate(Library_ID = str_replace_all(Library_ID, "-sanguinis.mapped_rmdup.cov",""))

# fwrite(sanguinis_cmc_cov, "05-results/sanguinis_cmc_indep_cov.tsv", quote = F, sep = "\t")


```

```{r}

sinensis_cmc_cov <-  fread("05-results/sinensis_cmc_indep_cov.tsv.gz") %>%
  as_tibble()
sanguinis_cmc_cov <-  fread("05-results/sanguinis_cmc_indep_cov.tsv.gz") %>%
  as_tibble()

# now add the genome accession to the table for filtering
sinensis_cmc_cov <- sinensis_cmc_cov %>%
  left_join(., genome_metadata, by = "Contig") %>%
  select(Assembly_accession, everything()) %>%
  filter(Contig != "genome")


# now add the genome accession to the table for filtering
sanguinis_cmc_cov <- sanguinis_cmc_cov %>%
  left_join(., genome_metadata, by = "Contig") %>%
  select(Assembly_accession, everything()) %>%
  filter(Contig != "genome")

```


```{r cmc_independent_coverages}

cmc_independent_coverages <- sinensis_cmc_cov %>%
  filter(Assembly_accession != "all") %>%
  filter(Depth > 0) %>%
  group_by(Library_ID, Assembly_accession) %>%
  summarize(bases_cov_min1X = sum(Breadth)) %>%
  ungroup() %>%
  full_join(., sinensis_cmc_cov %>%
              filter(Assembly_accession != "all") %>%
               select(Assembly_accession, Library_ID, Depth, Breadth) %>%
               filter(Depth >= 2) %>%
               group_by(Library_ID, Assembly_accession) %>%
               summarize(bases_cov_min2X = sum(Breadth)) %>%
               ungroup()) %>%
  full_join(., sinensis_cmc_cov %>%
              filter(Assembly_accession != "all") %>%
               select(Assembly_accession, Library_ID, Depth, Breadth) %>%
               filter(Depth >= 5) %>%
               group_by(Library_ID, Assembly_accession) %>%
               summarize(bases_cov_min5X = sum(Breadth)) %>%
               ungroup()) %>%
  left_join(., genome_lengths, by = "Assembly_accession") %>%
  group_by(Library_ID, Assembly_accession) %>%
  summarize(breadth_1X = bases_cov_min1X / GenomeLen * 100,
            breadth_2X = bases_cov_min2X / GenomeLen * 100,
            breadth_5X = bases_cov_min5X / GenomeLen * 100) %>%
  ungroup() %>%
  bind_rows(., sanguinis_cmc_cov %>%
            filter(Assembly_accession != "all") %>%
            filter(Depth > 0) %>%
            group_by(Library_ID, Assembly_accession) %>%
            summarize(bases_cov_min1X = sum(Breadth)) %>%
            ungroup() %>%
            full_join(., sanguinis_cmc_cov %>%
                         filter(Assembly_accession != "all") %>%
                         select(Assembly_accession, Library_ID, Depth, Breadth) %>%
                         filter(Depth >= 2) %>%
                         group_by(Library_ID, Assembly_accession) %>%
                         summarize(bases_cov_min2X = sum(Breadth)) %>%
                         ungroup()) %>%
            full_join(., sanguinis_cmc_cov %>%
                         filter(Assembly_accession != "all") %>%
                         select(Assembly_accession, Library_ID, Depth, Breadth) %>%
                         filter(Depth >= 5) %>%
                         group_by(Library_ID, Assembly_accession) %>%
                         summarize(bases_cov_min5X = sum(Breadth)) %>%
                         ungroup()) %>%
  left_join(., genome_lengths, by = "Assembly_accession") %>%
  group_by(Library_ID, Assembly_accession) %>%
  summarize(breadth_1X = bases_cov_min1X / GenomeLen * 100,
            breadth_2X = bases_cov_min2X / GenomeLen * 100,
            breadth_5X = bases_cov_min5X / GenomeLen * 100) %>%
  ungroup())

```

```{r}

cmc_independent_coverages %>%  select(Library_ID, Assembly_accession, breadth_2X) %>%
  arrange(Library_ID, desc(breadth_2X)) %>%
  left_join(., genome_metadata %>%
              select(Assembly_accession, GTDB_species)) %>%
  distinct() %>%
  left_join(., cmc_most_abund_strep, by = "Library_ID") %>%
  filter(Library_ID != "CMC032.B0101") %>%
  separate(GTDB_species, into = "map_species", sep = "_", extra = "drop") %>%
  separate(Species, into = "kraken_species", sep = "_", extra = "drop") %>%
  mutate(same_sp = map_species == kraken_species) %>%
  group_by(Library_ID) %>%
  slice_max(breadth_2X) %>%
  arrange(desc(same_sp), map_species) %>%
  filter(kraken_species == "sinensis")

```

```{r}
cmc_independent_coverages %>%
  pivot_longer(!Library_ID:Assembly_accession, names_to = "Depth", values_to = "Breadth") %>%
  filter(Depth == "breadth_1X") %>%
  left_join(., genome_metadata %>%
              select(Assembly_accession, GTDB_species)) %>%
  distinct() %>%
  mutate(Assembly_accession = fct_relevel(Assembly_accession, sp_order)) %>%
  full_join(., cmc_most_abund_strep %>%
               separate(Species, into = "species", sep = "_", extra = "drop"), by = "Library_ID") %>%
  filter(str_detect(species, "sinensis|sanguinis")) %>%
  ggplot(., aes(x = Assembly_accession, y = Breadth, fill = GTDB_species)) + # Species
         geom_boxplot(outlier.colour = NA) +
         geom_jitter(aes(shape = species), alpha = 0.5, width = 0.2) +
         scale_fill_manual(values = sp_colors) +
         scale_shape_manual(values = c(4, 1)) +
         # scale_shape_manual(values = c(8, 3, 6, 1)) +
         ylim(0,100) +
         theme_minimal(base_size = 10) +
         theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
         ylab("Breadth of genome covered at least 1X (%)") +
         ggtitle("Individual genome mapping")

cmc_independent_coverages %>%
  pivot_longer(!Library_ID:Assembly_accession, names_to = "Depth", values_to = "Breadth") %>%
  filter(Depth == "breadth_5X") %>%
  left_join(., genome_metadata %>%
              select(Assembly_accession, GTDB_species)) %>%
  distinct() %>%
  drop_na(Breadth) %>%
  mutate(Assembly_accession = fct_relevel(Assembly_accession, sp_order)) %>%
  full_join(., cmc_most_abund_strep %>%
              filter(Library_ID != "CMC032.B0101") %>%
               separate(Species, into = "species", sep = "_", extra = "drop"), by = "Library_ID") %>%
  filter(str_detect(species, "sinensis|sanguinis")) %>%
  ggplot(., aes(x = Assembly_accession, y = Breadth, fill = GTDB_species)) + # Species
         geom_boxplot(outlier.colour = NA) +
         geom_jitter(aes(shape = species), alpha = 0.5, width = 0.2) +
         scale_fill_manual(values = sp_colors) +
         scale_shape_manual(values = c(4, 1)) +
         # scale_shape_manual(values = c(8, 3, 6, 1)) +
         theme_minimal(base_size = 10) +
         theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
         ylim(0,100) +
         ylab("Breadth of genome covered at least 5X (%)") +
         ggtitle("Individual genome mapping")

```

```{r cov_independent}

cmc_indep_cov_plot <- cmc_independent_coverages %>%
  mutate(Library_ID = str_replace_all(Library_ID, ".SG1","")) %>%
  select(-breadth_2X, -breadth_5X) %>%
  left_join(., genome_metadata %>%
              select(Assembly_accession, GTDB_species) %>%
              rename(Assembly_species = GTDB_species)) %>%
  distinct() %>%
  full_join(., cmc_most_abund_strep %>%
               separate(Species, into = "species", sep = "_", extra = "drop"), by = "Library_ID") %>%
  filter(str_detect(species, "sinensis|sanguinis")) %>%
  drop_na(breadth_1X) %>%
  # get rid of the species cluster info so have only sanguinis/sinensis for plotting
  separate(Assembly_species, into = "Assembly_species", sep = "_", extra = "drop") %>%
  filter(Library_ID != "CMC032.B0101") %>%
  ggplot(.) +
         geom_point(aes(x = Assembly_species, y = breadth_1X, fill = species), shape = 21, color = "black") + # , fill = "#766df8"
         geom_line(aes(x = Assembly_species, y = breadth_1X, group = Library_ID), linetype="dotted") +
         theme_minimal(base_size = 12) +
         scale_fill_manual(values = sp_colors) +
         theme(axis.text.x = element_text(angle = 0, hjust = 0.5, size = 12),
               axis.text.y = element_text(size = 12)) +
         xlab("Genome") +
         ylab("% of genome covered at 1X") +
         facet_wrap(~species)
cmc_indep_cov_plot

cmc_indep_cov_box_plot<-  cmc_independent_coverages %>%
  mutate(Library_ID = str_replace_all(Library_ID, ".SG1","")) %>%
  select(-breadth_2X, -breadth_5X) %>%
  left_join(., genome_metadata %>%
              select(Assembly_accession, GTDB_species) %>%
              rename(Assembly_species = GTDB_species)) %>%
  distinct() %>%
  full_join(., cmc_most_abund_strep %>%
               separate(Species, into = "species", sep = "_", extra = "drop"), by = "Library_ID") %>%
  filter(str_detect(species, "sinensis|sanguinis")) %>%
  drop_na(breadth_1X) %>%
  # get rid of the species cluster info so have only sanguinis/sinensis for plotting
  separate(Assembly_species, into = "Assembly_species", sep = "_", extra = "drop") %>%
  select(-Assembly_accession) %>%
  filter(Library_ID != "CMC032.B0101") %>%
  pivot_wider(names_from = "Assembly_species", values_from = "breadth_1X") %>%
  mutate(Difference = sanguinis - sinensis,
         Slope = (sinensis - sanguinis) / (1-0)) %>%
  # filter(Slope >= 1 | Slope <= -1) %>%
  ggplot(., aes(x = species, y = Slope, fill = species)) + # Species
         geom_boxplot(outlier.colour = NA) +
         geom_jitter(aes(shape = species), alpha = 0.5, width = 0.2) +
         scale_fill_manual(values = sp_colors) +
         scale_shape_manual(values = c(4, 1)) +
         # scale_shape_manual(values = c(8, 3, 6, 1)) +
         theme_minimal(base_size = 12) +
         theme(axis.text.x = element_text(angle = 0, hjust = 0.5, size = 12),
               axis.text.y = element_text(size = 12)) +
         geom_hline(yintercept = 0, linetype = "dashed") +
         ylab("Slope") +
         xlab("Species") 
cmc_indep_cov_box_plot

```

```{r}

cmc_ss_indep_map <- cmc_indep_cov_plot + cmc_indep_cov_box_plot +
  plot_layout(widths = c(1.5, 1)) +
  plot_layout(guides = "collect")

cmc_ss_indep_map

# ggsave("./06-publication/main_figures/Figure_XX6/ss_independent_map_cmc.pdf", plot = cmc_ss_indep_map, device = "pdf",
#        scale = 1, width = 6, height = 4, units = c("in"), dpi = 300)

```

```{r, eval = F}
# sinensis
vcf_list_sinensis_cmc <- list.files(path = "./04-analysis/sinensis_sanguinis_mapping/non_ind_plaque/sinensis", pattern = ".vcf$", full.names = T)

vcf_cmc_sinensis_sum_snp <- map_dfr(vcf_list_sinensis_cmc, function(fn) {
  fread(fn, col.names = c("Contig", "POS", "ID","REF","ALT", "QUAL", "FILTER","INFO", "FORMAT","BAM"), sep = "\t", skip = 147, header = F) %>%
  mutate(Library_ID = basename(fn)) %>%
  as_tibble() %>%
  filter(FILTER == "PASS")
}) %>%
# remove the end of the file name from the Library_ID
  mutate(Library_ID = str_replace_all(Library_ID, ".sinensis.vcf","")) 

fwrite(vcf_cmc_sinensis_sum_snp, "05-results/vcf_cmc_sinensis_snp.tsv", quote = F, sep = "\t")

# sanguinis
vcf_list_sanguinis_cmc <- list.files(path = "./04-analysis/sinensis_sanguinis_mapping/non_ind_plaque/sanguinis", pattern = ".vcf$", full.names = T)

vcf_cmc_sanguinis_sum_snp <- map_dfr(vcf_list_sanguinis_cmc, function(fn) {
  fread(fn, col.names = c("Contig", "POS", "ID","REF","ALT", "QUAL", "FILTER","INFO", "FORMAT","BAM"), sep = "\t", skip = 31, header = F) %>%
  mutate(Library_ID = basename(fn)) %>%
  as_tibble() %>%
  filter(FILTER == "PASS")
}) %>%
# remove the end of the file name from the Library_ID
  mutate(Library_ID = str_replace_all(Library_ID, ".sanguinis.vcf","")) 


# fwrite(vcf_cmc_sanguinis_sum_snp, "05-results/vcf_cmc_sanguinis_snp.tsv", quote = F, sep = "\t")

```

```{r}
vcf_cmc_sinensis_snp <- fread("05-results/vcf_cmc_sinensis_snp.tsv.gz") %>%
  as_tibble()
vcf_cmc_sanguinis_snp <- fread("05-results/vcf_cmc_sanguinis_snp.tsv.gz") %>%
  as_tibble()

vcf_cmc_sinensis_sum_snp <- vcf_cmc_sinensis_snp %>%
  full_join(., genome_metadata, by = "Contig") %>%
  drop_na(Library_ID) %>%
  separate(INFO, into = "Depth", extra = "drop", sep = ";") %>%
  mutate(Depth = str_replace_all(Depth, "DP=",""),
         Depth = as.numeric(Depth)) %>% 
  filter(Depth >= 2) %>%
  group_by(Library_ID, Assembly_accession) %>%
  count() %>%
  ungroup() %>%
  left_join(., genome_metadata %>%
              select(Assembly_accession, Species, GTDB_species), by = "Assembly_accession") %>%
  distinct()


vcf_cmc_sanguinis_sum_snp <- vcf_cmc_sanguinis_snp %>%
  full_join(., genome_metadata, by = "Contig") %>%
  drop_na(Library_ID) %>%
  separate(INFO, into = "Depth", extra = "drop", sep = ";") %>%
  mutate(Depth = str_replace_all(Depth, "DP=",""),
         Depth = as.numeric(Depth)) %>% 
  filter(Depth >= 2) %>%
  group_by(Library_ID, Assembly_accession) %>%
  count() %>%
  ungroup() %>%
  left_join(., genome_metadata %>%
              select(Assembly_accession, Species, GTDB_species), by = "Assembly_accession") %>%
  distinct()

# combine together into 1 file
vcf_independent_snp <- vcf_cmc_sinensis_sum_snp %>%
  bind_rows(., vcf_cmc_sanguinis_sum_snp) %>%
  rename(no_snps_2X_cov = n)

```


```{r}
vcf_independent_snp %>%
  left_join(., genome_lengths) %>%
  full_join(., cmc_most_abund_strep %>%
               filter(Library_ID != "CMC032.B0101") %>%
               separate(Species, into = "species", sep = "_", extra = "drop"), by = "Library_ID") %>%
  mutate(proportion_snps = no_snps_2X_cov / GenomeLen,
         Assembly_accession = fct_relevel(Assembly_accession, sp_order)) %>%
  arrange(Assembly_accession) %>%
  ggplot(., aes(x = Assembly_accession, y = proportion_snps, fill = GTDB_species)) +
         geom_boxplot(outlier.colour = NA) +
         geom_jitter(aes(shape = species), alpha = 0.5, width = 0.2) +
         scale_shape_manual(values = c(8, 6, 4, 1)) +
         scale_fill_manual(values = sp_colors) +
         theme_minimal(base_size = 10) +
         theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
         ylab("% SNPs/Genome") +
         ggtitle("")

```

```{r}
vcf_independent_snp %>%
  left_join(., cmc_most_abund_strep %>%
               separate(Species, into = "species", sep = "_", extra = "drop"), by = "Library_ID") %>%
  filter(str_detect(species, "sinensis|sanguinis")) %>%
  left_join(., genome_lengths) %>%
  mutate(proportion_snps = no_snps_2X_cov / GenomeLen,
         Assembly_accession = fct_relevel(Assembly_accession, sp_order)) %>%
  rename(Assembly_species = GTDB_species) %>%
  arrange(Library_ID) %>%
  ggplot(.) +
         geom_point(aes(x = Assembly_species, y = proportion_snps, fill = species), shape = 21, color = "black") + # , fill = "#766df8"
         geom_line(aes(x = Assembly_species, y = proportion_snps, group = Library_ID), linetype="dotted") +
         theme_minimal(base_size = 12) +
         scale_fill_manual(values = sp_colors) +
         theme(axis.text.x = element_text(angle = 0, hjust = 0.5, size = 12),
               axis.text.y = element_text(size = 12)) +
         xlab("Genome") +
         ylab("Proportion of SNPs covered at 2X") +
         facet_wrap(~species)

```

```{r multiallelic_snps, eval = F}
# sinensis
tsv_list_sinensis_cmc <- list.files(path = "./04-analysis/sinensis_sanguinis_mapping/non_ind_plaque/sinensis", pattern = ".vcf.tsv$", full.names = T)

tsv_cmc_sinensis_sum_snp <- map_dfr(tsv_list_sinensis_cmc, function(fn) {
  fread(fn, col.names = c("Contig", "POS", "REF", "DP", "ALT"), sep = "\t") %>%
  mutate(Library_ID = basename(fn)) %>%
  as_tibble()
}) %>%
# remove the end of the file name from the Library_ID
  mutate(Library_ID = str_replace_all(Library_ID, ".sinensis.vcf.tsv","")) 

# fwrite(tsv_cmc_sinensis_sum_snp, "05-results/tsv_cmc_sinensis_snp.tsv", sep = "\t", quote = F)

# sanguinis
tsv_list_sanguinis_cmc <- list.files(path = "./04-analysis/sinensis_sanguinis_mapping/non_ind_plaque/sanguinis", pattern = ".vcf.tsv$", full.names = T)

tsv_cmc_sanguinis_sum_snp <- map_dfr(tsv_list_sanguinis_cmc, function(fn) {
  fread(fn, col.names = c("Contig", "POS", "REF", "DP", "ALT"), sep = "\t") %>%
  mutate(Library_ID = basename(fn)) %>%
  as_tibble()
}) %>%
# remove the end of the file name from the Library_ID
  mutate(Library_ID = str_replace_all(Library_ID, ".sanguinis.vcf.tsv","")) 

# fwrite(tsv_cmc_sanguinis_sum_snp, "05-results/tsv_cmc_sanguinis_snp.tsv", sep = "\t", quote = F)

```

```{r}

tsv_cmc_sinensis_snp <- fread("05-results/tsv_cmc_sinensis_snp.tsv.gz") %>%
  as_tibble()
tsv_cmc_sanguinis_snp <- fread("05-results/tsv_cmc_sanguinis_snp.tsv.gz") %>%
  as_tibble()

#. sinensis
tsv_cmc_sinensis_sum_snp <- tsv_cmc_sinensis_snp %>%
  group_by(Library_ID, Contig, POS) %>%
  count() %>%
  ungroup() %>%
  left_join(., genome_metadata %>%
              select(Assembly_accession, Contig, Species, GTDB_species), by = "Contig") %>%
  distinct()

# sanguinis
tsv_cmc_sanguinis_sum_snp <- tsv_cmc_sanguinis_snp %>%
  group_by(Library_ID, Contig, POS) %>%
  count() %>%
  ungroup() %>%
  left_join(., genome_metadata %>%
              select(Assembly_accession, Contig, Species, GTDB_species), by = "Contig") %>%
  distinct()



```


```{r}
# total multi-allelic snps
tsv_cmc_sinensis_sum_snp %>%
  bind_rows(., tsv_cmc_sanguinis_sum_snp) %>%
  filter(n > 1) %>%
  group_by(Library_ID, Species) %>%
  count(name = "multiallelic_snps") %>%
  ungroup() %>%
  mutate(Species = str_replace_all(Species, "Streptococcus", "S.")) %>%
  full_join(., cmc_most_abund_strep %>%
               filter(Library_ID != "CMC032.B0101") %>%
               separate(Species, into = "species", sep = "_", extra = "drop"), by = "Library_ID") %>%
  ggplot(., aes(x = Species, y = multiallelic_snps, fill = Species)) +
         geom_boxplot(outlier.colour = NA) +
         geom_jitter(aes(shape = species), alpha = 0.5, width = 0.2) +
         scale_shape_manual(values = c(8, 6, 4, 1)) +
         scale_fill_manual(values = c("#253494", "#C70E7B")) +
         theme_minimal(base_size = 10) +
         theme(axis.text.x = element_text(angle = 0, hjust = 0.5)) +
         ylab("# multi-allelic snps") +
         ggtitle("")

# % of multi-allelic snps out of all snps covered at least 2X
# maybe need to normalize this by genome length
tsv_cmc_sinensis_sum_snp %>%
  bind_rows(., tsv_cmc_sanguinis_sum_snp) %>%
  filter(n > 1) %>%
  group_by(Library_ID, Species) %>%
  count(name = "multiallelic_snps") %>%
  ungroup() %>%
  left_join(., vcf_independent_snp, by = c("Library_ID","Species")) %>%
  mutate(pct_multiallelic_snps = multiallelic_snps / no_snps_2X_cov * 100) %>%
  mutate(Species = str_replace_all(Species, "Streptococcus", "S.")) %>%
  full_join(., cmc_most_abund_strep %>%
               filter(Library_ID != "CMC032.B0101") %>%
               separate(Species, into = "species", sep = "_", extra = "drop"), by = "Library_ID") %>%
  ggplot(., aes(x = Species, y = pct_multiallelic_snps, fill = Species)) +
         geom_boxplot(outlier.colour = NA) +
         geom_jitter(aes(shape = species), alpha = 0.5, width = 0.2) +
         scale_shape_manual(values = c(8, 6, 4, 1)) +
         scale_fill_manual(values = c("#253494", "#C70E7B")) +
         theme_minimal(base_size = 10) +
         theme(axis.text.x = element_text(angle = 0, hjust = 0.5)) +
         ylab("% SNPs covered min 2X that are multiallelic") +
         ggtitle("")


```

```{r}

tsv_cmc_sinensis_sum_snp %>%
  bind_rows(., tsv_cmc_sanguinis_sum_snp) %>%
  filter(n == 2) %>%
  group_by(Library_ID, Species) %>%
  count(name = "biallelic") %>%
  ungroup() %>%
  full_join(., tsv_cmc_sinensis_sum_snp %>%
            bind_rows(., tsv_cmc_sanguinis_sum_snp) %>%
            filter(n > 2) %>%
            group_by(Library_ID, Species) %>%
            count(name = "multiallelic") %>%
            ungroup()) %>%
  pivot_longer(!Library_ID:Species, names_to = "snp_type", values_to = "snp_counts") %>%
  left_join(., vcf_independent_snp, by = c("Library_ID","Species")) %>%
  mutate(snp_pcts = snp_counts / no_snps_2X_cov * 100) %>%
  mutate(Species = str_replace_all(Species, "Streptococcus ", "")) %>%
  full_join(., cmc_most_abund_strep %>%
               filter(Library_ID != "CMC032.B0101") %>%
               separate(Species, into = "species", sep = "_", extra = "drop"), by = "Library_ID") %>%
  filter(str_detect(species, "sinensis|sanguinis")) %>%
  # filter(Species == species) %>%
  ggplot(., aes(x = Species, y = snp_pcts, fill = Species)) +
         geom_boxplot(outlier.colour = NA) +
         geom_jitter(aes(shape = species), alpha = 0.5, width = 0.2) +
         scale_shape_manual(values = c(4, 1)) +
         scale_fill_manual(values = c("#253494", "#C70E7B")) +
         theme_minimal(base_size = 10) +
         theme(axis.text.x = element_text(angle = 0, hjust = 0.5)) +
         # scale_y_log10() +
         # ylab("% SNPs covered min 2X that are multiallelic") +
         ggtitle("") +
         facet_wrap(~snp_type)
  
  
```

```{r}


# snp info per site
friday <- vcf_cmc_sinensis_snp %>%
  bind_rows(vcf_cmc_sanguinis_snp) %>%
  drop_na(Library_ID) %>%
  separate(INFO, into = "Depth", extra = "drop", sep = ";") %>%
  mutate(Depth = str_replace_all(Depth, "DP=",""),
         Depth = as.numeric(Depth)) %>% 
  # take only sites with coverage depth of at least 2
  filter(Depth >= 2) %>%
  # remove some unneeded columns for easier reading
  select(-ID, -ALT, -REF, -QUAL, -FILTER, -FORMAT, -BAM) %>%
  # add genome metadata
  left_join(., genome_metadata, by = "Contig") %>%
  # add the number of alleles per position
  left_join(., tsv_cmc_sinensis_sum_snp %>%
            bind_rows(., tsv_cmc_sanguinis_sum_snp) %>%
            rename(no_alleles = n)) %>%
  # filter(Library_ID == "CMC001.A0101") %>%
  mutate(no_alleles = ifelse(no_alleles >= 3, 3, no_alleles)) %>%
  filter(Library_ID != "CMC032.B0101") %>%
  group_by(Library_ID, Species, no_alleles) %>%
  count(name = "counts") %>%
  ungroup() %>%
  group_by(Library_ID, Species) %>%
  mutate(snp_pcts = counts / sum(counts) * 100) %>%
  ungroup() %>%
  # pivot_longer(!Library_ID:Species, names_to = "snp_type", values_to = "snp_counts") %>%
  left_join(., vcf_independent_snp, by = c("Library_ID","Species")) %>%
  # mutate(snp_pcts = snp_counts / no_snps_2X_cov * 100) %>%
  mutate(Species = str_replace_all(Species, "Streptococcus ", "")) %>%
  full_join(., cmc_most_abund_strep %>%
               filter(Library_ID != "CMC032.B0101") %>%
               separate(Species, into = "species", sep = "_", extra = "drop"), by = "Library_ID") %>%
  filter(str_detect(species, "sinensis|sanguinis")) 

friday %>%
  filter(Species != species) %>%
  ggplot(., aes(x = Species, y = snp_pcts, fill = Species)) +
         geom_boxplot(outlier.colour = NA) +
         geom_jitter(aes(shape = species), alpha = 0.5, width = 0.2) +
         scale_shape_manual(values = c(4, 1)) +
         scale_fill_manual(values = c("#253494", "#C70E7B", "yellow")) +
         theme_minimal(base_size = 10) +
         theme(axis.text.x = element_text(angle = 0, hjust = 0.5)) +
         # scale_y_log10() +
         # ylab("% SNPs covered min 2X that are multiallelic") +
         ggtitle("") +
         facet_wrap(~no_alleles)
  
  
```

#### Shannon index evenness of coverage
```{r cmc_load_independent_cov, eval = F}
# Sinensis
sinensis_list_cov_cmc <- list.files(path = "./04-analysis/sinensis_sanguinis_mapping/non_ind_plaque/sinensis", pattern = ".d.cov", full.names = T)

sinensis_cmc_d_cov <- map_dfr(sinensis_list_cov_cmc, function(fn) {
  fread(fn, col.names = c("Contig", "Ntd", "Depth"), sep = "\t") %>%
  mutate(Library_ID = basename(fn)) %>%
  as_tibble()
}) %>%
  arrange(Library_ID) %>%
  # remove the end of the file name from the Library_ID
  mutate(Library_ID = str_replace_all(Library_ID, "-sinensis.mapped_rmdup.d.cov",""))

# Sanguinis
sanguinis_list_cov_cmc <- list.files(path = "./04-analysis/sinensis_sanguinis_mapping/non_ind_plaque/sanguinis", pattern = ".d.cov", full.names = T)

sanguinis_cmc_d_cov <- map_dfr(sanguinis_list_cov_cmc, function(fn) {
  fread(fn, col.names = c("Contig", "Ntd", "Depth"), sep = "\t") %>%
  lazy_dt() %>%
  mutate(Library_ID = basename(fn)) %>%
  mutate(Base = str_c(Contig,"_",Ntd)) %>%
  select(-Contig,-Ntd) %>%
  # unite(Base = unite(Base, Contig:Ntd, sep = "_") %>%
  pivot_wider(names_from = "Base", values_from = "Depth") %>%
  as_tibble()
}) %>%
  bind_rows(.) %>%
  arrange(Library_ID) %>%
# remove the end of the file name from the Library_ID
  mutate(Library_ID = str_replace_all(Library_ID, "-sanguinis.mapped_rmdup.d.cov",""))

```

```{r shannon, eval = F}
# Sinensis
sinensis_cmc_d_cov.mat <- sinensis_cmc_d_cov %>%
  # merge the contigs and the ntd 
  # each base site is treated as a species
  unite(Base, Contig:Ntd, sep = "_") %>%
  pivot_wider(names_from = "Base", values_from = "Depth") %>%
  column_to_rownames("Library_ID") %>%
  as.matrix(.)

sinensis_cmc_d_cov.shannon <- as.data.frame(vegan::diversity(sinensis_cmc_d_cov.mat, index = "shannon"))
names(sinensis_cmc_d_cov.shannon)[1] <- "Shannon_index"

# now plot Shannon index vs breadth at 1X coverage
sinensis_cmc_d_cov.shannon %>%
  left_join(., cmc_independent_coverages %>%
  filter(Depth == "cov_1X") %>%
    filter(Assembly_accession == "GCF_000767835.1"))

# calculate genome coverage variance
# calculate mean of cooverage at each base from .d.cov file and then calculate the sd and square the sd

sanguinis_cmc_d_cov.mat <- sanguinis_cmc_d_cov %>%
  column_to_rownames("Library_ID") %>%
  as.matrix()

sanguinis_cmc_d_cov.shannon <- as.data.frame(vegan::diversity(sanguinis_cmc_d_cov.mat, index = "shannon"))
names(sanguinis_cmc_d_cov.shannon)[1] <- "Shannon_index"


```



```{r, eval = F}

# Raincloud plots
sp_counts %>%
  left_join(., lib_metadata %>%
              select(Study, Full, Secondary_sample_accession) %>%
              rename(Library_ID = Secondary_sample_accession) %>%
              distinct(), by = "Library_ID") %>%
  ggplot(., aes(x = Study, y = Total, fill = Study)) + 
  ## add half-violin from {ggdist} package
  ggdist::stat_halfeye(
    ## custom bandwidth
    adjust = .5, 
    ## adjust height
    width = .6, 
    ## move geom to the right
    justification = -.2, 
    ## remove slab interval
    .width = 0, 
    point_colour = NA
  ) + 
  geom_boxplot(
    width = .12, 
    ## remove outliers
    outlier.color = NA, ## `outlier.shape = NA` works as well
    color = "grey30"
  ) +
  ## add dot plots from {ggdist} package
  ggdist::stat_dots(
    ## orientation to the left
    side = "left", 
    ## move geom to the left
    justification = 1.1, 
    ## adjust grouping (binning) of observations 
    binwidth = 1
  ) + 
  ## remove white space on the left
  coord_cartesian(xlim = c(0, NA)) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)) +
  facet_grid(~Full, scales = "free_x", space = 'free')
  # +
  # scale_fill_manual(values = Time_period_colors)

```


### CMC Coverage with MAGs

```{r cmc_mag_load_cov, eval = F}

sss_list_mag_cmc <- list.files(path = "./04-analysis/sinensis_sanguinis_mapping/deep_evo_mags/non_ind_plaque/", pattern = ".cov", full.names = T)

sss_cmc_mag_cov <- map_dfr(sss_list_mag_cmc, function(fn) {
  fread(fn, col.names = c("Contig", "Depth", "Breadth","Genome_length","Proportion_covered"), sep = "\t") %>%
  mutate(Library_ID = basename(fn)) %>%
  as_tibble()
}) %>%
  arrange(Library_ID) %>%
  filter(Contig != "genome") %>%
  # now add the genome accession to the table for filtering
  # remove the end of the file name from the Library_ID
  mutate(Library_ID = str_replace_all(Library_ID, "-mag_ss.mapped_rmdup.cov","")) 

# fwrite(sss_cmc_mag_cov, "05-results/sss_cmc_mag_cov.tsv", quote = F, sep = "\t")

```

```{r}
# read in the mag metadata table
mag_metadata <- fread("./00-documentation/deep_evo_mag_metadata.tsv")

sss_cmc_mag_cov <- fread("05-results/sss_cmc_mag_cov.tsv.gz") %>%
  as_tibble()

sss_cmc_mag_cov <- sss_cmc_mag_cov %>%
  inner_join(., genome_metadata %>%
              bind_rows(., mag_metadata)) %>%
  # full_join(., mag_metadata, by = c("Assembly_accession","Contig", "Species","GTDB_species")) %>%
  select(Assembly_accession, everything()) 

```


```{r cmc_mag_genome_coverages}

Genomes <- genome_metadata %>%
  filter(str_detect(Assembly_accession, "GCF_013343115.1|GCF_000767835.1")) %>%
  bind_rows(., mag_metadata) %>%
  select(Assembly_accession) %>%
  unique() %>%
  pull()

tot_genome_length <- fread("./00-documentation/mag_ss_strep.fa.fai", sep = "\t", col.names = c("Contig","genome_length","other1","other2","other3")) %>%
  as_tibble() %>%
  left_join(., mag_metadata) %>%
  drop_na(Assembly_accession) %>%
  group_by(Assembly_accession) %>%
  summarize(GenomeLen = sum(genome_length)) %>%
  bind_rows(., genome_lengths)

cmc_mag_genomes_coverage <- sss_cmc_mag_cov %>%
  filter(Assembly_accession != "all") %>%
  filter(Depth > 0) %>%
  group_by(Library_ID, Assembly_accession) %>%
  summarize(bases_cov_min1X = sum(Breadth)) %>%
  ungroup() %>%
  full_join(., sss_cmc_mag_cov %>%
              filter(Assembly_accession != "all") %>%
               select(Assembly_accession, Library_ID, Depth, Breadth) %>%
               filter(Depth >= 2) %>%
               group_by(Library_ID, Assembly_accession) %>%
               summarize(bases_cov_min2X = sum(Breadth)) %>%
               ungroup()) %>%
  full_join(., sss_cmc_mag_cov %>%
              filter(Assembly_accession != "all") %>%
               select(Assembly_accession, Library_ID, Depth, Breadth) %>%
               filter(Depth >= 5) %>%
               group_by(Library_ID, Assembly_accession) %>%
               summarize(bases_cov_min5X = sum(Breadth)) %>%
               ungroup()) %>%
  full_join(., tot_genome_length, by = "Assembly_accession") %>%
  group_by(Library_ID, Assembly_accession) %>%
  summarize(breadth_1X = bases_cov_min1X / GenomeLen * 100,
            breadth_2X = bases_cov_min2X / GenomeLen * 100,
            breadth_5X = bases_cov_min5X / GenomeLen * 100) %>%
  ungroup() %>%
  pivot_longer(!Library_ID:Assembly_accession, names_to = "Depth", values_to = "Breadth")

# Genomes <- c("GCF_013343115.1","GCF_000767835.1")

cmc_mag_genomes_coverage %>%
  select(Assembly_accession) %>%
  unique()

```


```{r cmc_mag_coverages}
# species with max breadth of coverage at 1X depth
cmc_mag_genomes_coverage %>%
  filter(Depth == "breadth_1X") %>%
  group_by(Library_ID) %>%
  slice_max(Breadth) %>%
  left_join(., genome_metadata %>%
              bind_rows(., mag_metadata) %>%
              select(Assembly_accession, GTDB_species)) %>%
  distinct()
  
# species with max breadth of coverage at 2X depth
cmc_mag_genomes_coverage %>%
  filter(Depth == "breadth_2X") %>%
  group_by(Library_ID) %>%
  slice_max(Breadth) %>%
  left_join(., genome_metadata %>%
              bind_rows(., mag_metadata) %>%
              select(Assembly_accession, GTDB_species)) %>%
  distinct() %>%
  # remove CMC032.B b/c it has no coverage at 2X depth (poor sample)
  filter(Library_ID != "CMC032.B0101.SG1")

# species with max breadth of coverage at 5X depth
cmc_mag_genomes_coverage %>%
  filter(Depth == "breadth_5X") %>%
  group_by(Library_ID) %>%
  slice_max(Breadth) %>%
  left_join(., genome_metadata %>%
              bind_rows(., mag_metadata) %>%
              select(Assembly_accession, GTDB_species)) %>%
  distinct() %>%
  # remove CMC032.B b/c it has no coverage at 5X depth (poor sample)
  filter(Library_ID != "CMC032.B0101.SG1")
 
```

```{r}
cmc_mag_genomes_coverage_plot <- cmc_mag_genomes_coverage %>%
  filter(Depth != "breadth_2X") %>%
  left_join(., genome_metadata %>%
              select(Assembly_accession, GTDB_species)) %>%
  distinct() %>%
  full_join(., cmc_most_abund_strep %>%
               filter(Library_ID != "CMC032.B0101") %>%
               separate(Species, into = "species", sep = "_", extra = "drop"), by = "Library_ID") %>%
  filter(Library_ID != "CMC032.B0101") %>%  
  mutate(Assembly_accession = fct_relevel(Assembly_accession, sp_order)) %>%
  ggplot(., aes(x = Assembly_accession, y = Breadth, fill = Assembly_accession)) + # Species
         geom_boxplot(outlier.colour = NA) +
         geom_jitter(aes(shape = species), alpha = 0.5, width = 0.2) +
         scale_shape_manual(values = c(8, 6, 4, 1)) +
         scale_fill_manual(values = c("#253494", "#C70E7B", "#EC921D", "#f9ca7f", "#fbe1b6", "#fef7ec")) +
         ylim(0,100) +
         theme_minimal(base_size = 10) +
         theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)) +
         ylab("Breadth of genome covered (%)") +
         xlab("Assembly accession") +
         facet_wrap(~Depth)
cmc_mag_genomes_coverage_plot

# ggsave("./06-publication/supplemental_figures/Sup_fig_S17/cmc_mag_genomes_coverage_plot.pdf", plot = cmc_mag_genomes_coverage_plot, device = "pdf",
#        scale = 1, width = 8, height = 5, units = c("in"), dpi = 300)

```


























