---
title: "Dental Arcade (Fagernaes2022) Strep group distributions"
author: "Irina Velsko"
date: "`r format(Sys.time(), '%b %d, %Y')`"
output:
    github_document:
        fig_width: 8
        fig_height: 6
        toc: true
---

```{r load_libraries, echo = F, message = F}
library(knitr)
library(data.table)
library(janitor)
library(tidyverse)
library(patchwork)
opts_chunk$set(echo=F, warning=F, message=F, dpi=150)
```

Set the working directory of the notebook to the parent directory of the 
notebook itself.  

```{r setup}
knitr::opts_knit$set(root.dir = normalizePath(".."))
```

```{r strep_groups}
# read in the updated Strep group table with dRep cluster groups added

# strep_groups <- fread("./00-documentation/dRep_strep_groups.tsv") %>%
#   # remove the extrac column with the old dRep
#   select(-Clade_Consensus) %>%
#   # make a factor for plotting
#   mutate(dRep = fct_relevel(dRep, "Sanguinis","Mitis","Salivarius","Anginosus","Bovis","Pyogenic","Mutans","Other_oral","Other","Unknown"))

# file with species names and clade designations
gtdb_clades <- fread("./00-documentation/dRep_gtdb_clades.tsv")

gtdb_clades <- gtdb_clades %>%
  mutate(Clade = fct_relevel(Clade, "Sanguinis","Mitis","Salivarius","Anginosus","Bovis","Pyogenic","Mutans","Downei","Other","Unknown"))

```


```{r}
# set colors to resemble James' figure

clade_colors <- c("Sanguinis" = "#a50026",
                  "Mitis" = "#d73027",
                  "Salivarius" = "#f46d43",
                  "Anginosus" = "#fee090",
                  "Bovis" = "#abd9e9",
                  "Pyogenic" = "#74add1",
                  "Mutans" = "#4575b4",
                  "Downei" = "#313695",
                  "Other" = "#4d4d4d",
                  "Unknown" = "#e0e0e0")

genus_colors <- c("Streptococcus" = "#a50026", "Other" = "#e0e0e0")

```


## Kraken2 GTDB r202
```{r load_MALT_RefSeq_data}

# read in the species table
da_calc_raw <- fread("./05-results/anc_calc.kraken2.gtdb.report_mpa.tsv.gz") 

# filter to have only Streptococcus
da_calc_strep_sp <- da_calc_raw %>% 
  # select only DA manuscript samples
  select(matches("Lineage|CDM")) %>%
  filter(str_detect(Lineage, "s__s__")) %>%
  separate(Lineage, into = c("domain","phylum","class","order","family","genus","Species"), sep = "\\|", extra = "merge") %>%
  select(-c("domain","phylum","class","order","family","genus")) %>%
  mutate(Species = str_replace_all(Species, "s__s__","")) %>% 
  filter(str_detect(Species, "Streptococcus"))


# metadata
da_metadata <- fread("https://raw.githubusercontent.com/ivelsko/smoking_calculus/main/00-documentation.backup/DA_metadata.tsv") %>%
  mutate(Jawbone = str_replace_all(Jawbone, "Mandibula","Mandible"))
# Order the FDI numbers
FDI_order <- c("18", "17", "16", "15", "14", "13", "12", "11", # right maxilla
               "21", "22", "23", "24", "25", "26", "27", "28", # left maxilla
               "48", "47", "46", "45", "44", "43", "42", "41", # right mandible
               "31", "32", "33", "34", "35", "36", "37", "38")

```


```{r malt_rs_graphs}

# set the order of samples based on proportion of Sanguinis and agninosis
# need to get the proportion of each for this
# then arrange by proportion

sample_order_rs <- da_calc_strep_sp %>%
  # join with the Strep grup table for plotting
  inner_join(., gtdb_clades) %>%
  select(-Species) %>%
  select(Clade, everything()) %>%
  # long-format
  gather("Library_ID","Counts", 2:ncol(.)) %>%
  # sum together all species per group
  group_by(Library_ID, Clade) %>%
  summarize(Reads = sum(Counts)) %>%
  # transpose
  spread(Clade, Reads) %>%
  # convert table to proportions
  adorn_percentages(denominator = "row") %>%
  # arrange by Sanguinis and for the ones w/o Sanguinis, by Anginosus
  arrange(desc(Sanguinis), Anginosus)%>%
  pull(Library_ID)


da_calc_strep_sp %>%
  # remove the bone samples
  # join with the Strep grup table for plotting
  inner_join(., gtdb_clades) %>%
  select(Species, Clade, everything()) %>%
  # convert to long-format
  gather("Library_ID","Counts", 3:ncol(.)) %>%
  mutate(Library_ID = fct_relevel(Library_ID, sample_order_rs)) %>%
  dplyr::group_by(Library_ID, Clade) %>%
  summarize(Count_sum = sum(Counts)) %>%
  ggplot(., aes(x = Library_ID, y = Count_sum, fill = Clade)) +
         geom_bar(position = "fill", stat = "identity") + # , color = "black"
         theme_minimal(base_size = 10) +
         scale_fill_manual(values = clade_colors) +
         theme(axis.text.x = element_text(angle = 90, hjust = 1),
               axis.text = element_text(size = 10)) +
         # scale_y_continuous(breaks=scales::pretty_breaks(n=6)) +
         geom_hline(yintercept = 0.5, linetype = "dotted") +
         ylab("Proportion Strep group") +
         ggtitle("")

```

By individual sorted by tooth location
```{r CM55}
sample_order_cm55 <- da_metadata  %>%
  filter(Individual == "CM55") %>%
  mutate(ToothNr_FDI = as.character(ToothNr_FDI),
         ToothNr_FDI = fct_relevel(ToothNr_FDI, FDI_order)) %>%
  arrange(ToothNr_FDI) %>%
  filter(Type != "Bone") %>%
  select(LibraryID, Jawbone, ToothNr_FDI) %>%
  rename(Library_ID = LibraryID)

lib_order_cm55 <- da_metadata  %>%
  filter(Individual == "CM55") %>%
  mutate(ToothNr_FDI = as.character(ToothNr_FDI),
         ToothNr_FDI = fct_relevel(ToothNr_FDI, FDI_order)) %>%
  arrange(ToothNr_FDI) %>%
  filter(Type != "Bone") %>%
  select(LibraryID, Jawbone, ToothNr_FDI) %>%
  rename(Library_ID = LibraryID) %>%
  pull(Library_ID)


cm55_gp <- da_calc_strep_sp %>%
  # join with the Strep group table for plotting
  inner_join(., gtdb_clades) %>%
  select(Species, Clade, everything()) %>%
  # convert to long-format
  gather("Library_ID","Counts", 3:ncol(.)) %>%
  inner_join(., sample_order_cm55, by = "Library_ID") %>%
  dplyr::group_by(ToothNr_FDI, Clade) %>%
  summarize(Count_sum = sum(Counts)) %>%
  ungroup() %>%
  ggplot(., aes(x = ToothNr_FDI, y = Count_sum, fill = Clade)) +
         geom_bar(position = "fill", stat = "identity") + # , color = "black"
         theme_minimal(base_size = 10) +
         scale_fill_manual(values = clade_colors) +
         theme(axis.text.x = element_text(size = 8)) +
         scale_y_continuous(labels = function(x) paste0(x*100)) + # Multiply by 100
         # geom_hline(yintercept = 0.5, linetype = "dotted") +
         ylab("Percent") +
         xlab("Tooth Nr. (FDI)") +
         ggtitle("")
cm55_gp

# ggsave("./06-publication/main_figures/Figure_XX6/cm55_gp.pdf", plot = cm55_gp, device = "pdf",
#        scale = 1, width = 9, height = 5, units = c("in"), dpi = 300)


```

```{r calc_strep_prop}

strep_prop <- da_calc_raw %>%
  # select only DA manuscript samples
  select(matches("Lineage|CDM")) %>%
  filter(str_detect(Lineage, "s__s__")) %>%
  separate(Lineage, into = c("domain","phylum","class","order","family","genus","Species"), sep = "\\|", extra = "merge") %>%
  select(-c("domain","phylum","class","order","family","genus")) %>%
  mutate(Species = str_replace_all(Species, "s__s__","")) %>%
  # make a column with Strep or other
  mutate(Genus = ifelse(str_detect(Species,"Strep"),"Streptococcus","Other")) %>%
  # remove Species column leaving Genus column
  select(Genus, everything()) %>%
  select(-Species) %>%
  # convert to long format
  pivot_longer(!Genus, names_to =  "Library_ID", values_to = "Counts") %>%
  group_by(Library_ID, Genus) %>%
  # sum all Strep read counts and all Other read counts
  summarize(Reads = sum(Counts)) %>%
  ungroup() %>%
  spread(Genus, Reads) %>%
  # convert to proportions
  adorn_percentages() %>%
  # remove CDM samples that weren't part of the DA study
  filter(!str_detect(Library_ID, "CDM019|CDM020|CDM031|CDM032|CDM033"))


```


```{r genus_cm55}

# individual teeth
cm55_st <- strep_prop %>%
  pivot_longer(!Library_ID, names_to = "Genus", values_to = "Counts") %>%
  # gather("Genus","Counts", 2:ncol(.)) %>%
  inner_join(., sample_order_cm55, by = "Library_ID") %>%
  group_by(ToothNr_FDI,Genus) %>%
  summarize(Pct = mean(Counts)) %>%
  arrange(ToothNr_FDI) %>%
  mutate(ToothNr_FDI = fct_relevel(ToothNr_FDI, FDI_order)) %>%
  arrange(ToothNr_FDI) %>%
  ggplot(., aes(x = ToothNr_FDI, y = Pct, fill = Genus)) +
         geom_bar(position = "fill", stat = "identity") + # , color = "black"
         # geom_text(aes(label = "15"), vjust= 0, hjust = 0, size = 2) +
         theme_minimal(base_size = 10) +
         scale_fill_manual(values = genus_colors) +
         theme(axis.text.x = element_text(angle = 0, hjust = 0.5),
               axis.text = element_text(size = 10)) +
         scale_y_continuous(labels = function(x) paste0(x*100)) + # Multiply by 100
         # geom_hline(yintercept = 0.5, linetype = "dotted") +
         ylab("Percent") +
         xlab("Tooth Nr. (FDI)") +
         ggtitle("")
cm55_st

# average across teeth
cm55_avg_plot <- strep_prop %>%
  gather("Genus","Counts", 2:ncol(.)) %>%
  inner_join(., sample_order_cm55, by = "Library_ID") %>%
  group_by(Genus) %>%
  summarize(Avg_Proportion = mean(Counts),
            SD_Proportion = sd(Counts)) %>%
  ungroup() %>%
  mutate(Sample = "one") %>%
  ggplot(., aes(x = Sample, y = Avg_Proportion, fill = Genus)) +
         geom_bar(position = "stack", stat = "identity") + # , color = "black"
         geom_errorbar(aes(ymin=Avg_Proportion-SD_Proportion, ymax=Avg_Proportion+SD_Proportion), width=.2) +
         theme_minimal(base_size = 10) +
         scale_fill_manual(values = genus_colors) +
         theme(axis.text = element_text(size = 10),
               axis.text.x = element_blank()) +
         scale_y_continuous(labels = function(x) paste0(x*100), limits = c(0, 1)) + # Multiply by 100
         ylab("Percent") +
         xlab("Average")
cm55_avg_plot

# ggsave("./06-publication/main_figures/Figure_XX6/cm55_st.pdf", plot = cm55_st, device = "pdf",
#        scale = 1, width = 9, height = 5, units = c("in"), dpi = 300)

```

```{r cm55_points}

aardvark <- da_calc_raw %>% 
  filter(str_detect(Lineage, "s__s__")) %>%
  separate(Lineage, into = c("domain","phylum","class","order","family","genus","Species"), sep = "\\|", extra = "merge") %>%
  select(-c("domain","phylum","class","order","family","genus")) %>%
  mutate(Species = str_replace_all(Species, "s__s__","")) %>%
  # make a column with Strep or other
  mutate(Genus_inc = ifelse(str_detect(Species,"Streptococcus"),"Streptococcus", "NonStrep")) %>%
  left_join(., gtdb_clades , by = "Species") %>%
  # remove Species column leaving Genus column
  mutate(Genus = replace_na(as.character(Clade), "NonStrep")) %>%
  select(Genus, everything()) %>%
  select(-matches("Species|Clade|Genus_inc")) %>%
  # convert to long format
  gather("Library_ID","Counts", 2:ncol(.)) %>%
  inner_join(., sample_order_cm55, by = "Library_ID") %>%
  group_by(Library_ID, Genus) %>%
  # sum all Strep read counts and all Other read counts
  summarize(Reads = sum(Counts)) %>%
  spread(Genus, Reads) %>%
  # convert to proportions
  adorn_percentages() %>%
  ungroup() %>%
  # rearrange column order
  select(Library_ID, NonStrep, Sanguinis, Anginosus, everything()) %>%
  # now sum counts for columns we're not interested in 
  mutate(OtherStrep = select(., Bovis:Salivarius) %>% rowSums()) %>%
  # rearrange column order again and drop the unwanted columns
  select(Library_ID, NonStrep, Sanguinis, Anginosus) %>%
  pivot_longer(!Library_ID, names_to = "Genus", values_to = "Counts") %>%
  # order the Library ID by 
  mutate(Library_ID = fct_relevel(Library_ID, sample_order_rs),
         Counts = Counts + 0.0001) %>%
         # Genus = fct_relevel(Genus, "NonStrep","OtherStrep","Sanguinis","Anginosus")) %>%
  filter(str_detect(Genus, "Sanguinis|Anginosus"))  %>%
  filter(Genus != "OtherStrep")

cm55_points <- aardvark %>%
  left_join(., da_metadata %>% select(LibraryID, ToothNr_FDI) %>% rename(Library_ID = LibraryID), by = "Library_ID") %>%
  group_by(ToothNr_FDI,Genus) %>%
  summarize(Pct = mean(Counts)) %>%
  ungroup() %>%
  mutate(ToothNr_FDI =  as.character(ToothNr_FDI)) %>%
  mutate(ToothNr_FDI = fct_relevel(ToothNr_FDI, FDI_order)) %>%
  arrange(ToothNr_FDI) %>%
  mutate(Percent = Pct * 100) %>%
  ggplot(., aes(x = ToothNr_FDI, y = Percent, shape = Genus, bg = Genus)) +
         geom_point(size = 2.0, color = "grey50") + # , color = "black"
         theme_minimal(base_size = 10) +
         scale_fill_manual(values = clade_colors) + # c("#fee090","#a50026")
         scale_shape_manual(values = c(21,24,23,22)) +
         theme(axis.text.x = element_text(angle = 0, hjust = 0.5, size = 8),
               axis.text = element_text(size = 10)) +
         scale_y_log10(limits = c(0.01, 11)) +
         labs(fill = "Clade", shape = "Clade") +
         ylab("Percent") +
         xlab("Tooth Nr. (FDI)")

cm55_points

```

## CM59

```{r CM59}
sample_order_cm59 <- da_metadata  %>%
  filter(Individual == "CM59") %>%
  mutate(ToothNr_FDI = as.character(ToothNr_FDI),
         ToothNr_FDI = fct_relevel(ToothNr_FDI, FDI_order)) %>%
  arrange(ToothNr_FDI) %>%
  filter(Type != "Bone") %>%
  select(LibraryID, Jawbone, ToothNr_FDI) %>%
  rename(Library_ID = LibraryID)

lib_order_cm59 <- da_metadata  %>%
  filter(Individual == "CM59") %>%
  mutate(ToothNr_FDI = as.character(ToothNr_FDI),
         ToothNr_FDI = fct_relevel(ToothNr_FDI, FDI_order)) %>%
  arrange(ToothNr_FDI) %>%
  filter(Type != "Bone") %>%
  select(LibraryID, Jawbone, ToothNr_FDI) %>%
  rename(Library_ID = LibraryID) %>%
  pull(Library_ID)


cm59_gp <- da_calc_raw %>%
  filter(str_detect(Lineage, "s__s__")) %>%
  separate(Lineage, into = c("domain","phylum","class","order","family","genus","Species"), sep = "\\|", extra = "merge") %>%
  select(-c("domain","phylum","class","order","family","genus")) %>%
  mutate(Species = str_replace_all(Species, "s__s__","")) %>%
  filter(str_detect(Species, "Streptococcus")) %>%
  # join with the Strep grup table for plotting
  inner_join(., gtdb_clades) %>%
  select(Species, Clade, everything()) %>%
  # convert to long-format
  gather("Library_ID","Counts", 3:ncol(.)) %>%
  inner_join(., sample_order_cm59, by = "Library_ID") %>%
  dplyr::group_by(ToothNr_FDI, Clade) %>%
  summarize(Count_sum = sum(Counts)) %>%
  ungroup() %>%
  ggplot(., aes(x = ToothNr_FDI, y = Count_sum, fill = Clade)) +
         geom_bar(position = "fill", stat = "identity") + # , color = "black"
         theme_minimal(base_size = 10) +
         scale_fill_manual(values = clade_colors) +
         theme(axis.text.x = element_text(size = 8)) +
         scale_y_continuous(labels = function(x) paste0(x*100)) + # Multiply by 100
         # geom_hline(yintercept = 0.5, linetype = "dotted") +
         ylab("Percent") +
         xlab("Tooth Nr. (FDI)") +
         ggtitle("")
cm59_gp

```


```{r genus_cm59}
# individual teeth
cm59_st <- strep_prop %>%
  gather("Genus","Counts", 2:ncol(.)) %>%
  inner_join(., sample_order_cm59, by = "Library_ID") %>%
  group_by(ToothNr_FDI,Genus) %>%
  summarize(Pct = mean(Counts)) %>%
  arrange(ToothNr_FDI) %>%
  mutate(ToothNr_FDI = fct_relevel(ToothNr_FDI, FDI_order)) %>%
  arrange(ToothNr_FDI) %>%
  ggplot(., aes(x = ToothNr_FDI, y = Pct, fill = Genus)) +
         geom_bar(position = "fill", stat = "identity") + # , color = "black"
         # geom_text(aes(label = "15"), vjust= 0, hjust = 0, size = 2) +
         theme_minimal(base_size = 10) +
         scale_fill_manual(values = genus_colors) +
         theme(axis.text.x = element_text(angle = 0, hjust = 0.5),
               axis.text = element_text(size = 10)) +
         scale_y_continuous(labels = function(x) paste0(x*100)) + # Multiply by 100
         # geom_hline(yintercept = 0.5, linetype = "dotted") +
         ylab("Percent") +
         xlab("Tooth Nr. (FDI)") +
         ggtitle("")
cm59_st

# average across teeth
strep_prop %>%
  gather("Genus","Counts", 2:ncol(.)) %>%
  inner_join(., sample_order_cm59, by = "Library_ID") %>%
  group_by(Genus) %>%
  summarize(Avg_Proportion = mean(Counts),
            SD_Proportion = sd(Counts)) %>%
  ungroup() %>%
  mutate(Sample = "one") %>%
  ggplot(., aes(x = Sample, y = Avg_Proportion, fill = Genus)) +
         geom_bar(position = "stack", stat = "identity") + # , color = "black"
         geom_errorbar(aes(ymin=Avg_Proportion-SD_Proportion, ymax=Avg_Proportion+SD_Proportion), width=.2) +
         theme_minimal(base_size = 10) +
         scale_fill_manual(values = genus_colors) +
         theme(axis.text = element_text(size = 10),
               axis.text.x = element_blank()) +
         scale_y_continuous(labels = function(x) paste0(x*100), limits = c(0, 1)) + # Multiply by 100
         ylab("Percent") +
         xlab("Average") +
         ggtitle("")


```

```{r cm59_points}

aardvark <- da_calc_raw %>% 
  filter(str_detect(Lineage, "s__s__")) %>%
  separate(Lineage, into = c("domain","phylum","class","order","family","genus","Species"), sep = "\\|", extra = "merge") %>%
  select(-c("domain","phylum","class","order","family","genus")) %>%
  mutate(Species = str_replace_all(Species, "s__s__","")) %>%
  # make a column with Strep or other
  mutate(Genus_inc = ifelse(str_detect(Species,"Streptococcus"),"Streptococcus", "NonStrep")) %>%
  left_join(., gtdb_clades , by = "Species") %>%
  # remove Species column leaving Genus column
  mutate(Genus = replace_na(as.character(Clade), "NonStrep")) %>%
  select(Genus, everything()) %>%
  select(-matches("Species|Clade|Genus_inc")) %>%
  # convert to long format
  gather("Library_ID","Counts", 2:ncol(.)) %>%
  inner_join(., sample_order_cm59, by = "Library_ID") %>%
  group_by(Library_ID, Genus) %>%
  # sum all Strep read counts and all Other read counts
  summarize(Reads = sum(Counts)) %>%
  spread(Genus, Reads) %>%
  # convert to proportions
  adorn_percentages() %>%
  ungroup() %>%
  # rearrange column order
  select(Library_ID, NonStrep, Sanguinis, Anginosus, everything()) %>%
  # now sum counts for columns we're not interested in 
  mutate(OtherStrep = select(., Bovis:Salivarius) %>% rowSums()) %>%
  # rearrange column order again and drop the unwanted columns
  select(Library_ID, NonStrep, Sanguinis, Anginosus) %>%
  pivot_longer(!Library_ID, names_to = "Genus", values_to = "Counts") %>%
  # order the Library ID by 
  mutate(Library_ID = fct_relevel(Library_ID, sample_order_rs),
         Counts = Counts + 0.0001) %>%
         # Genus = fct_relevel(Genus, "NonStrep","OtherStrep","Sanguinis","Anginosus")) %>%
  filter(str_detect(Genus, "Sanguinis|Anginosus"))  %>%
  filter(Genus != "OtherStrep")

cm59_points <- aardvark %>%
  left_join(., da_metadata %>% select(LibraryID, ToothNr_FDI) %>% rename(Library_ID = LibraryID), by = "Library_ID") %>%
  group_by(ToothNr_FDI,Genus) %>%
  summarize(Pct = mean(Counts)) %>%
  ungroup() %>%
  mutate(ToothNr_FDI =  as.character(ToothNr_FDI)) %>%
  mutate(ToothNr_FDI = fct_relevel(ToothNr_FDI, FDI_order)) %>%
  arrange(ToothNr_FDI) %>%
  mutate(Percent = Pct * 100) %>%
  ggplot(., aes(x = ToothNr_FDI, y = Percent, shape = Genus, bg = Genus)) +
         geom_point(size = 2.0, color = "grey50") + # , color = "black"
         theme_minimal(base_size = 10) +
         scale_fill_manual(values = clade_colors) + # c("#fee090","#a50026")
         scale_shape_manual(values = c(21,24,23,22)) +
         theme(axis.text.x = element_text(angle = 0, hjust = 0.5, size = 8),
               axis.text = element_text(size = 10)) +
         scale_y_log10(limits = c(0.01, 10)) +
         labs(fill = "Clade", shape = "Clade") +
         ylab("Percent") +
         xlab("Tooth Nr. (FDI)")

cm59_points

```

## CM82

```{r CM82}
sample_order_cm82 <- da_metadata  %>%
  filter(Individual == "CM82") %>%
  mutate(ToothNr_FDI = as.character(ToothNr_FDI),
         ToothNr_FDI = fct_relevel(ToothNr_FDI, FDI_order)) %>%
  arrange(ToothNr_FDI) %>%
  filter(Type != "Bone") %>%
  select(LibraryID, Jawbone, ToothNr_FDI) %>%
  rename(Library_ID = LibraryID)

lib_order_cm82 <- da_metadata  %>%
  filter(Individual == "CM82") %>%
  mutate(ToothNr_FDI = as.character(ToothNr_FDI),
         ToothNr_FDI = fct_relevel(ToothNr_FDI, FDI_order)) %>%
  arrange(ToothNr_FDI) %>%
  filter(Type != "Bone") %>%
  select(LibraryID, Jawbone, ToothNr_FDI) %>%
  rename(Library_ID = LibraryID) %>%
  pull(Library_ID)


cm82_gp <- da_calc_raw %>%
  filter(str_detect(Lineage, "s__s__")) %>%
  separate(Lineage, into = c("domain","phylum","class","order","family","genus","Species"), sep = "\\|", extra = "merge") %>%
  select(-c("domain","phylum","class","order","family","genus")) %>%
  mutate(Species = str_replace_all(Species, "s__s__","")) %>%
  filter(str_detect(Species, "Streptococcus")) %>%
  # join with the Strep grup table for plotting
  inner_join(., gtdb_clades) %>%
  select(Species, Clade, everything()) %>%
  # convert to long-format
  gather("Library_ID","Counts", 3:ncol(.)) %>%
  inner_join(., sample_order_cm82, by = "Library_ID") %>%
  dplyr::group_by(ToothNr_FDI, Clade) %>%
  summarize(Count_sum = sum(Counts)) %>%
  ungroup() %>%
  ggplot(., aes(x = ToothNr_FDI, y = Count_sum, fill = Clade)) +
         geom_bar(position = "fill", stat = "identity") + # , color = "black"
         theme_minimal(base_size = 10) +
         scale_fill_manual(values = clade_colors) +
         theme(axis.text.x = element_text(size = 8)) +
         scale_y_continuous(labels = function(x) paste0(x*100)) + # Multiply by 100
         # geom_hline(yintercept = 0.5, linetype = "dotted") +
         ylab("Percent") +
         xlab("Tooth Nr. (FDI)") +
         ggtitle("")
cm82_gp

```

```{r genus_cm82}

# individual teeth
cm82_st <- strep_prop %>%
  gather("Genus","Counts", 2:ncol(.)) %>%
  inner_join(., sample_order_cm82, by = "Library_ID") %>%
  group_by(ToothNr_FDI,Genus) %>%
  summarize(Pct = mean(Counts)) %>%
  arrange(ToothNr_FDI) %>%
  mutate(ToothNr_FDI = fct_relevel(ToothNr_FDI, FDI_order)) %>%
  arrange(ToothNr_FDI) %>%
  ggplot(., aes(x = ToothNr_FDI, y = Pct, fill = Genus)) +
         geom_bar(position = "fill", stat = "identity") + # , color = "black"
         # geom_text(aes(label = "15"), vjust= 0, hjust = 0, size = 2) +
         theme_minimal(base_size = 10) +
         scale_fill_manual(values = genus_colors) +
         theme(axis.text.x = element_text(angle = 0, hjust = 0.5),
               axis.text = element_text(size = 10)) +
         scale_y_continuous(labels = function(x) paste0(x*100)) + # Multiply by 100
         # geom_hline(yintercept = 0.5, linetype = "dotted") +
         xlab("Tooth Nr. (FDI)") +
         ylab("Percent") +
         ggtitle("")
cm82_st

# average across all teeth
strep_prop %>%
  gather("Genus","Counts", 2:ncol(.)) %>%
  inner_join(., sample_order_cm82, by = "Library_ID") %>%
  group_by(Genus) %>%
  summarize(Avg_Proportion = mean(Counts),
            SD_Proportion = sd(Counts)) %>%
  ungroup() %>%
  mutate(Sample = "one") %>%
  ggplot(., aes(x = Sample, y = Avg_Proportion, fill = Genus)) +
         geom_bar(position = "stack", stat = "identity") + # , color = "black"
         geom_errorbar(aes(ymin=Avg_Proportion-SD_Proportion, ymax=Avg_Proportion+SD_Proportion), width=.2) +
         theme_minimal(base_size = 10) +
         scale_fill_manual(values = genus_colors) +
         theme(axis.text = element_text(size = 10),
               axis.text.x = element_blank()) +
         scale_y_continuous(labels = function(x) paste0(x*100), limits = c(0, 1)) + # Multiply by 100
         ylab("Percent") +
         xlab("Average") +
         ggtitle("")

```

```{r cm82_points}

aardvark <- da_calc_raw %>% 
  filter(str_detect(Lineage, "s__s__")) %>%
  separate(Lineage, into = c("domain","phylum","class","order","family","genus","Species"), sep = "\\|", extra = "merge") %>%
  select(-c("domain","phylum","class","order","family","genus")) %>%
  mutate(Species = str_replace_all(Species, "s__s__","")) %>%
  # make a column with Strep or other
  mutate(Genus_inc = ifelse(str_detect(Species,"Streptococcus"),"Streptococcus", "NonStrep")) %>%
  left_join(., gtdb_clades , by = "Species") %>%
  # remove Species column leaving Genus column
  mutate(Genus = replace_na(as.character(Clade), "NonStrep")) %>%
  select(Genus, everything()) %>%
  select(-matches("Species|Clade|Genus_inc")) %>%
  # convert to long format
  gather("Library_ID","Counts", 2:ncol(.)) %>%
  inner_join(., sample_order_cm82, by = "Library_ID") %>%
  group_by(Library_ID, Genus) %>%
  # sum all Strep read counts and all Other read counts
  summarize(Reads = sum(Counts)) %>%
  spread(Genus, Reads) %>%
  # convert to proportions
  adorn_percentages() %>%
  ungroup() %>%
  # rearrange column order
  select(Library_ID, NonStrep, Sanguinis, Anginosus, everything()) %>%
  # now sum counts for columns we're not interested in 
  mutate(OtherStrep = select(., Bovis:Salivarius) %>% rowSums()) %>%
  # rearrange column order again and drop the unwanted columns
  select(Library_ID, NonStrep, Sanguinis, Anginosus) %>%
  pivot_longer(!Library_ID, names_to = "Genus", values_to = "Counts") %>%
  # order the Library ID by 
  mutate(Library_ID = fct_relevel(Library_ID, sample_order_rs),
         Counts = Counts + 0.0001) %>%
         # Genus = fct_relevel(Genus, "NonStrep","OtherStrep","Sanguinis","Anginosus")) %>%
  filter(str_detect(Genus, "Sanguinis|Anginosus"))  %>%
  filter(Genus != "OtherStrep")

cm82_points <- aardvark %>%
  left_join(., da_metadata %>% select(LibraryID, ToothNr_FDI) %>% rename(Library_ID = LibraryID), by = "Library_ID") %>%
  group_by(ToothNr_FDI,Genus) %>%
  summarize(Pct = mean(Counts)) %>%
  ungroup() %>%
  mutate(ToothNr_FDI =  as.character(ToothNr_FDI)) %>%
  mutate(ToothNr_FDI = fct_relevel(ToothNr_FDI, FDI_order)) %>%
  arrange(ToothNr_FDI) %>%
  mutate(Percent = Pct * 100) %>%
  ggplot(., aes(x = ToothNr_FDI, y = Percent, shape = Genus, bg = Genus)) +
         geom_point(size = 2.0, color = "grey50") + # , color = "black"
         theme_minimal(base_size = 10) +
         scale_fill_manual(values = clade_colors) + # c("#fee090","#a50026")
         scale_shape_manual(values = c(21,24,23,22)) +
         theme(axis.text.x = element_text(angle = 0, hjust = 0.5, size = 8),
               axis.text = element_text(size = 10)) +
         scale_y_log10(limits = c(0.01, 10)) +
         labs(fill = "Clade", shape = "Clade") +
         ylab("Percent") +
         xlab("Tooth Nr. (FDI)")

cm82_points

```

## CM165

```{r CM165}
sample_order_cm165 <- da_metadata  %>%
  filter(Individual == "CM165") %>%
  mutate(ToothNr_FDI = as.character(ToothNr_FDI),
         ToothNr_FDI = fct_relevel(ToothNr_FDI, FDI_order)) %>%
  arrange(ToothNr_FDI) %>%
  filter(Type != "Bone") %>%
  select(LibraryID, Jawbone, ToothNr_FDI) %>%
  rename(Library_ID = LibraryID)

lib_order_cm165 <- da_metadata  %>%
  filter(Individual == "CM165") %>%
  mutate(ToothNr_FDI = as.character(ToothNr_FDI),
         ToothNr_FDI = fct_relevel(ToothNr_FDI, FDI_order)) %>%
  arrange(ToothNr_FDI) %>%
  filter(Type != "Bone") %>%
  select(LibraryID, Jawbone, ToothNr_FDI) %>%
  rename(Library_ID = LibraryID) %>%
  pull(Library_ID)


cm165_gp <- da_calc_raw %>%
  filter(str_detect(Lineage, "s__s__")) %>%
  separate(Lineage, into = c("domain","phylum","class","order","family","genus","Species"), sep = "\\|", extra = "merge") %>%
  select(-c("domain","phylum","class","order","family","genus")) %>%
  mutate(Species = str_replace_all(Species, "s__s__","")) %>%
  filter(str_detect(Species, "Streptococcus")) %>%
  # join with the Strep grup table for plotting
  inner_join(., gtdb_clades) %>%
  select(Species, Clade, everything()) %>%
  # convert to long-format
  gather("Library_ID","Counts", 3:ncol(.)) %>%
  inner_join(., sample_order_cm165, by = "Library_ID") %>%
  dplyr::group_by(ToothNr_FDI, Clade) %>%
  summarize(Count_sum = sum(Counts)) %>%
  ungroup() %>%
  # inner_join(., sample_order_cm165, by = "Library_ID") %>%
  # arrange(ToothNr_FDI) %>%
  # mutate(Library_ID = fct_relevel(Library_ID, lib_order_cm165)) %>%
  ggplot(., aes(x = ToothNr_FDI, y = Count_sum, fill = Clade)) +
         geom_bar(position = "fill", stat = "identity") + # , color = "black"
         theme_minimal(base_size = 10) +
         scale_fill_manual(values = clade_colors) +
         theme(axis.text.x = element_text(angle = 0, hjust = 0.5, size = 8)) +
         scale_y_continuous(labels = function(x) paste0(x*100)) + # Multiply by 100
         # geom_hline(yintercept = 0.5, linetype = "dotted") +
         ylab("Percent") +
         xlab("Tooth Nr. (FDI)") +
         ggtitle("")
cm165_gp

```

```{r genus_cm165}

# individual teeth
cm165_st <- strep_prop %>%
  gather("Genus","Counts", 2:ncol(.)) %>%
  inner_join(., sample_order_cm165, by = "Library_ID") %>%
  group_by(ToothNr_FDI,Genus) %>%
  summarize(Pct = mean(Counts)) %>%
  arrange(ToothNr_FDI) %>%
  mutate(ToothNr_FDI = fct_relevel(ToothNr_FDI, FDI_order)) %>%
  arrange(ToothNr_FDI) %>%
  ggplot(., aes(x = ToothNr_FDI, y = Pct, fill = Genus)) +
         geom_bar(position = "fill", stat = "identity") + # , color = "black"
         # geom_text(aes(label = "15"), vjust= 0, hjust = 0, size = 2) +
         theme_minimal(base_size = 10) +
         scale_fill_manual(values = genus_colors) +
         theme(axis.text.x = element_text(angle = 0, hjust = 0.5),
               axis.text = element_text(size = 10)) +
         scale_y_continuous(labels = function(x) paste0(x*100)) + # Multiply by 100
         # geom_hline(yintercept = 0.5, linetype = "dotted") +
         ylab("Percent") +
         xlab("Tooth Nr. (FDI)") +
         ggtitle("")
cm165_st

# average across all teeth
cm165_avg_plot <- strep_prop %>%
  gather("Genus","Counts", 2:ncol(.)) %>%
  inner_join(., sample_order_cm165, by = "Library_ID") %>%
  group_by(Genus)%>%
  summarize(Avg_Proportion = mean(Counts),
            SD_Proportion = sd(Counts)) %>%
  ungroup() %>%
  # mutate(up = Avg_Proportion+SD_Proportion, 
  #        down = Avg_Proportion-SD_Proportion)
  mutate(Sample = "one") %>%
  ggplot(., aes(x = Sample, y = Avg_Proportion, fill = Genus)) +
         geom_bar(position = "stack", stat = "identity") + # , color = "black"
         geom_errorbar(aes(ymin=Avg_Proportion-SD_Proportion, ymax=Avg_Proportion+SD_Proportion), width = 0.2) +
         theme_minimal(base_size = 10) +
         scale_fill_manual(values = genus_colors) +
         theme(axis.text = element_text(size = 10),
               axis.text.x = element_blank()) +
         scale_y_continuous(labels = function(x) paste0(x*100), limits = c(0, 1)) + # Multiply by 100
         ylab("Percent") +
         xlab("Average") +
         ggtitle("")
cm165_avg_plot


```

```{r cm165_points}

aardvark <- da_calc_raw %>% 
  filter(str_detect(Lineage, "s__s__")) %>%
  separate(Lineage, into = c("domain","phylum","class","order","family","genus","Species"), sep = "\\|", extra = "merge") %>%
  select(-c("domain","phylum","class","order","family","genus")) %>%
  mutate(Species = str_replace_all(Species, "s__s__","")) %>%
  # make a column with Strep or other
  mutate(Genus_inc = ifelse(str_detect(Species,"Streptococcus"),"Streptococcus", "NonStrep")) %>%
  left_join(., gtdb_clades , by = "Species") %>%
  # remove Species column leaving Genus column
  mutate(Genus = replace_na(as.character(Clade), "NonStrep")) %>%
  select(Genus, everything()) %>%
  select(-matches("Species|Clade|Genus_inc")) %>%
  # convert to long format
  gather("Library_ID","Counts", 2:ncol(.)) %>%
  inner_join(., sample_order_cm165, by = "Library_ID") %>%
  group_by(Library_ID, Genus) %>%
  # sum all Strep read counts and all Other read counts
  summarize(Reads = sum(Counts)) %>%
  spread(Genus, Reads) %>%
  # convert to proportions
  adorn_percentages() %>%
  ungroup() %>%
  # rearrange column order
  select(Library_ID, NonStrep, Sanguinis, Anginosus, everything()) %>%
  # now sum counts for columns we're not interested in 
  mutate(OtherStrep = select(., Bovis:Salivarius) %>% rowSums()) %>%
  # rearrange column order again and drop the unwanted columns
  select(Library_ID, NonStrep, Sanguinis, Anginosus) %>%
  pivot_longer(!Library_ID, names_to = "Genus", values_to = "Counts") %>%
  # order the Library ID by 
  mutate(Library_ID = fct_relevel(Library_ID, sample_order_rs),
         Counts = Counts + 0.0001) %>%
         # Genus = fct_relevel(Genus, "NonStrep","OtherStrep","Sanguinis","Anginosus")) %>%
  filter(str_detect(Genus, "Sanguinis|Anginosus"))  %>%
  filter(Genus != "OtherStrep")

cm165_points <- aardvark %>%
  left_join(., da_metadata %>% select(LibraryID, ToothNr_FDI) %>% rename(Library_ID = LibraryID), by = "Library_ID") %>%
  group_by(ToothNr_FDI,Genus) %>%
  summarize(Pct = mean(Counts)) %>%
  ungroup() %>%
  mutate(ToothNr_FDI =  as.character(ToothNr_FDI)) %>%
  mutate(ToothNr_FDI = fct_relevel(ToothNr_FDI, FDI_order)) %>%
  arrange(ToothNr_FDI) %>%
  mutate(Percent = Pct * 100) %>%
  ggplot(., aes(x = ToothNr_FDI, y = Percent, shape = Genus, bg = Genus)) +
         geom_point(size = 2.0, color = "grey50") + # , color = "black"
         theme_minimal(base_size = 10) +
         scale_fill_manual(values = clade_colors) + # c("#fee090","#a50026")
         scale_shape_manual(values = c(21,24,23,22)) +
         theme(axis.text.x = element_text(angle = 0, hjust = 0.5, size = 8),
               axis.text = element_text(size = 10)) +
         scale_y_log10(limits = c(0.01, 10)) +
         labs(fill = "Clade", shape = "Clade") +
         ylab("Percent") +
         xlab("Tooth Nr. (FDI)")

cm165_points

```

```{r da_main_fig}

da_main_fig <- (cm55_avg_plot | cm55_gp) /
          (cm165_avg_plot | cm165_gp) +
          plot_layout(widths = c(1,3)) +
          plot_layout(guides = 'collect')

da_main_fig

# ggsave("./06-publication/main_figures/Figure_XX5/strep_props_da.pdf", plot = da_main_fig,
#        device = "pdf", scale = 1, width = 8, height = 5, units = c("in"), dpi = 300)


```


```{r da_sup_fig}

da_fig <- (cm55_gp | cm59_gp | cm82_gp | cm165_gp) /
          (cm55_st | cm59_st | cm82_st | cm165_st) /
          (cm55_points | cm59_points| cm82_points| cm165_points) +
          # plot_layout(heights = c(1,1,1)) +
          plot_layout(guides = 'collect')

da_fig

# ggsave("./06-publication/supplemental_figures/Sup_fig_S13/strep_props_da.pdf", plot = da_fig,
#        device = "pdf", scale = 1, width = 14, height = 8.5, units = c("in"), dpi = 300)


```

```{r}

strep_prop %>%
  full_join(., da_metadata %>%
              select(LibraryID, Individual) %>%
              rename(Library_ID = LibraryID), by = "Library_ID") %>%
  as_tibble() %>%
  drop_na(Streptococcus) %>%
  mutate(Strep = ifelse(Individual == "CM165", "Low","High")) %>%
  group_by(Strep) %>%
  summarize(meanStrep = mean(Streptococcus),
            sdStrep = sd(Streptococcus)) %>%
  ungroup()


strep_prop %>%
  full_join(., da_metadata %>%
              select(LibraryID, Individual) %>%
              rename(Library_ID = LibraryID), by = "Library_ID") %>%
  as_tibble() %>%
  drop_na(Streptococcus) %>%
  mutate(Strep = ifelse(Individual == "CM165", "Low","High")) %>%
  rstatix::wilcox_test(., Streptococcus ~ Strep) %>%
  full_join(., strep_prop %>%
            full_join(., da_metadata %>%
                      select(LibraryID, Individual) %>%
                      rename(Library_ID = LibraryID), by = "Library_ID") %>%
            as_tibble() %>%
            drop_na(Streptococcus) %>%
            mutate(Strep = ifelse(Individual == "CM165", "Low","High")) %>%
            rstatix::wilcox_effsize(., Streptococcus ~ Strep))


```













