---
title: "Ancient calculus Strep clade distributions"
author: "Irina Velsko"
date: "`r format(Sys.time(), '%b %d, %Y')`"
output:
    github_document:
        fig_width: 8
        fig_height: 6
        toc: true
---

```{r load_libraries, echo = F, message = F}
library(knitr)
library(data.table)
library(janitor)
library(variancePartition)
library(tidyverse)
library(patchwork)
opts_chunk$set(echo=F, warning=F, message=F, dpi=150)
```

Set the working directory of the notebook to the parent directory of the 
notebook itself.  

```{r setup}
knitr::opts_knit$set(root.dir = normalizePath(".."))
```


```{r}
# file with species names and clade designations
gtdb_clades <- fread("./00-documentation/dRep_gtdb_clades.tsv")

gtdb_clades <- gtdb_clades %>%
  mutate(Clade = fct_relevel(Clade, "Sanguinis","Mitis","Salivarius","Anginosus","Bovis","Pyogenic","Mutans","Downei","Other","Unknown"))

```


```{r metadata}

# get only industrial saliva from the metadata table
lib_metadata <- fread("./00-documentation/strep_clades_metadata.tsv") %>%
  filter(str_detect(Sample_group, "ancient_calculus")) %>%
  distinct()

```


```{r}
# set colors to resemble James' figure

clade_colors <- c("Sanguinis" = "#a50026",
                  "Mitis" = "#d73027",
                  "Salivarius" = "#f46d43",
                  "Anginosus" = "#fee090",
                  "Bovis" = "#abd9e9",
                  "Pyogenic" = "#74add1",
                  "Mutans" = "#4575b4",
                  "Downei" = "#313695",
                  "Other" = "#4d4d4d",
                  "Unknown" = "#e0e0e0")

genus_colors <- c("Streptococcus" = "#a50026", "Other" = "#e0e0e0")

```


## Kraken2 GTDB r202 table
```{r load_data}
# read in the species table. It has the column names already
anc_calc_raw <- fread("./05-results/anc_calc.kraken2.gtdb.report_mpa.tsv.gz") 

anc_names <- fread("./05-results/anc_calc_names.tsv", header = F)  %>%
  rename(Library_ID = 1) %>%
  mutate(Library_ID = str_replace_all(Library_ID, ".SG1.1", ""),
         Library_ID = str_replace_all(Library_ID, ".SG1", ""))

# filter to have only species and remove all species with <1000 reads assigned
# even filtering out taxa with <10000 counts doesn't help
anc_calc_strep_sp <- anc_calc_raw %>% 
  filter(str_detect(Lineage, "s__s__")) %>%
  separate(Lineage, into = c("domain","phylum","class","order","family","genus","Species"), sep = "\\|", extra = "merge") %>%
  select(-c("domain","phylum","class","order","family","genus")) %>%
  mutate(Species = str_replace_all(Species, "s__s__","")) %>%
  filter(str_detect(Species, "Streptococcus")) %>%
  # remove Radcliffe soil and dentin
  select(-matches("CSS|CSD"))

```

Read in poorly-preserved samples. 
```{r cuperdec_poor}
# read in table of poorly-preserved samples as determined by cuperdec
poor_samples <- fread("./05-results/cuperdec_anc_calc_poor_samples.tsv") %>%
  pull(Sample)

poor_df <- fread("./05-results/cuperdec_anc_calc_poor_samples.tsv") %>%
  mutate(Preservation = "Poor") %>%
  rename(Library_ID = Sample)

```


### Velsko2022
```{r strep_clade_props_velsko2022}

# set the order of samples based on proportion of Sanguinis and agninosis
# need to get the proportion of each for this
# then arrange by proportion

sample_order_rs <- anc_calc_strep_sp  %>%
  # remove poorly-preserved samples
  select(-matches(poor_samples %>% str_c(collapse = "|"))) %>%
  # select only Velsko2022
  column_to_rownames("Species") %>%
  select(matches(lib_metadata %>% filter(Study == "Velsko2022") %>% pull(Sample_alias))) %>%
  # remove CMB for AHC figure
  select(-matches("CMB|ELR|IVE")) %>%
  rownames_to_column("Species") %>%
  # join with the Strep grup table for plotting
  inner_join(., gtdb_clades) %>%
  select(-Species) %>%
  select(Clade, everything()) %>%
  # long-format
  pivot_longer(!Clade, names_to = "Library_ID", values_to = "Counts") %>%
  # sum together all species per group
  group_by(Library_ID, Clade) %>%
  summarize(Reads = sum(Counts)) %>%
  # transpose
  pivot_wider(names_from = "Clade", values_from = "Reads") %>%
  # convert table to proportions
  adorn_percentages(denominator = "row") %>%
  # arrange by Sanguinis and for the ones w/o Sanguinis, by Anginosus
  arrange(desc(Sanguinis), Anginosus)%>%
  pull(Library_ID)


middenbeemster_clades <- anc_calc_strep_sp %>%
  # remove poorly-preserved samples
  select(-matches(poor_samples %>% str_c(collapse = "|"))) %>%
  # select only Velsko2022
  column_to_rownames("Species") %>%
  select(matches(lib_metadata %>% filter(Study == "Velsko2022") %>% pull(Sample_alias))) %>%
  # remove CMB for AHC figure
  select(-matches("CMB|ELR|IVE")) %>%
  rownames_to_column("Species") %>%
  filter(str_detect(Species, "Streptococcus")) %>%
  # join with the Strep grup table for plotting
  inner_join(., gtdb_clades) %>%
  select(Species, Clade, everything()) %>%
  # convert to long-format
  pivot_longer(!Species:Clade, names_to = "Library_ID",values_to = "Counts") %>%
  mutate(Library_ID = fct_relevel(Library_ID, sample_order_rs)) %>%
  dplyr::group_by(Library_ID, Clade) %>%
  summarize(Count_sum = sum(Counts)) %>%
  ggplot(., aes(x = Library_ID, y = Count_sum, fill = Clade)) +
         geom_bar(position = "fill", stat = "identity") + # , color = "black"
         theme_minimal(base_size = 8) +
         scale_fill_manual(values = clade_colors) +
         theme(axis.text.x = element_blank()) +
         # theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5),
         #       axis.text = element_text(size = 8)) +
         # scale_y_continuous(breaks=scales::pretty_breaks(n=6)) +
         scale_y_continuous(labels = function(x) paste0(x*100)) + # Multiply by 100
         ylab("Percent") +
         labs(fill = "Clade") +
         xlab("") +
         ggtitle("") 
middenbeemster_clades

```

```{r rs_strep_proportion_velsko2022}

strep_prop <- anc_calc_raw %>% 
  # remove poorly-preserved samples
  select(-matches(poor_samples %>% str_c(collapse = "|"))) %>%
  # select only Velsko2022
  column_to_rownames("Lineage") %>%
  select(matches(lib_metadata %>% filter(Study == "Velsko2022") %>% pull(Sample_alias))) %>%
  # remove CMB for AHC figure
  select(-matches("CMB|ELR|IVE")) %>%
  rownames_to_column("Lineage") %>%
  filter(str_detect(Lineage, "s__s__")) %>%
  separate(Lineage, into = c("domain","phylum","class","order","family","genus","Species"), sep = "\\|", extra = "merge") %>%
  select(-c("domain","phylum","class","order","family","genus")) %>%
  mutate(Species = str_replace_all(Species, "s__s__","")) %>%
  # make a column with Strep or other
  mutate(Genus = ifelse(str_detect(Species,"Strep"),"Streptococcus","Other")) %>%
  # remove Species column leaving Genus column
  select(Genus, everything()) %>%
  select(-Species) %>%
  # convert to long format
  pivot_longer(!Genus, names_to = "Library_ID", values_to = "Counts") %>%
  group_by(Library_ID, Genus) %>%
  # sum all Strep read counts and all Other read counts
  summarize(Reads = sum(Counts)) %>%
  spread(Genus, Reads) %>%
  # convert to proportions
  adorn_percentages() %>%
  ungroup()

middenbeemster_strep_prop <- strep_prop %>%
  pivot_longer(!Library_ID, names_to = "Genus", values_to = "Counts") %>%
  mutate(Library_ID = fct_relevel(Library_ID, sample_order_rs)) %>%
  arrange(Library_ID) %>%
  ggplot(., aes(x = Library_ID, y = Counts, fill = Genus)) +
         geom_bar(stat = "identity") + # , color = "black"
         theme_minimal(base_size = 8) +
         scale_fill_manual(values = genus_colors) +
         theme(axis.text.x = element_blank()) +
         # theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5),
         #       axis.text = element_text(size = 8)) +
         # scale_y_continuous(breaks=scales::pretty_breaks(n=6)) +
         scale_y_continuous(labels = function(x) paste0(x*100)) + # Multiply by 100
         ylab("Percent") +
         xlab("") +
        ggtitle("")
middenbeemster_strep_prop

```


```{r sanguinis_anginosus_velsko2022}

aardvark <- anc_calc_raw %>% 
  # remove poorly-preserved samples
  select(-matches(poor_samples %>% str_c(collapse = "|"))) %>%
  # select only Velsko2022
  column_to_rownames("Lineage") %>%
  select(matches(lib_metadata %>% filter(Study == "Velsko2022") %>% pull(Sample_alias))) %>%
  # remove CMB for AHC figure
  select(-matches("CMB|ELR|IVE")) %>%
  rownames_to_column("Lineage") %>%
  filter(str_detect(Lineage, "s__s__")) %>%
  separate(Lineage, into = c("domain","phylum","class","order","family","genus","Species"), sep = "\\|", extra = "merge") %>%
  select(-c("domain","phylum","class","order","family","genus")) %>%
  mutate(Species = str_replace_all(Species, "s__s__","")) %>%
  # make a column with Strep or other
  mutate(Genus_inc = ifelse(str_detect(Species,"Streptococcus"),"Streptococcus", "NonStrep")) %>%
  left_join(., gtdb_clades , by = "Species") %>%
  # remove Species column leaving Genus column
  mutate(Genus = replace_na(as.character(Clade), "NonStrep")) %>%
  select(Genus, everything()) %>%
  select(-matches("Species|Clade|Genus_inc")) %>%
  # convert to long format
  pivot_longer(!Genus, names_to = "Library_ID", values_to = "Counts") %>%
  group_by(Library_ID, Genus) %>%
  # sum all Strep read counts and all Other read counts
  summarize(Reads = sum(Counts)) %>%
  pivot_wider(names_from = "Genus", values_from = "Reads") %>%
  # convert to proportions
  adorn_percentages() %>%
  ungroup() %>%
  # rearrange column order
  select(Library_ID, NonStrep, Sanguinis, Anginosus, everything()) %>%
  # now sum counts for columns we're not interested in 
  mutate(OtherStrep = select(., Bovis:Salivarius) %>% rowSums()) %>%
  # rearrange column order again and drop the unwanted columns
  select(Library_ID, NonStrep, Sanguinis, Anginosus, OtherStrep) %>%
  pivot_longer(!Library_ID, names_to = "Genus", values_to = "Counts") %>%
  # order the Library ID by 
  mutate(Library_ID = fct_relevel(Library_ID, sample_order_rs),
         Counts = Counts + 0.0001) %>%
         # Genus = fct_relevel(Genus, "NonStrep","OtherStrep","Sanguinis","Anginosus")) %>%
  filter(str_detect(Genus, "Sanguinis|Anginosus")) 

middenbeemster_points <- aardvark%>%
  arrange(Library_ID) %>%
  mutate(Percent = Counts * 100) %>%
  mutate(Library_ID = fct_drop(Library_ID)) %>%
  ggplot(., aes(x = Library_ID, y = Percent, shape = Genus, bg = Genus)) +
         geom_point(size = 0.5, color = "grey50") + # , color = "black"
         theme_minimal(base_size = 8) +
         scale_fill_manual(values = c("#fee090","#a50026")) +
         scale_shape_manual(values = c(21,24)) +
         theme(axis.text.x = element_blank()) +
         # theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5),
         #       axis.text = element_text(size = 8)) +
         scale_y_log10() +
         labs(fill = "Clade", shape = "Clade") +
         ylab("Percent") +
         xlab("Sample") +
         ggtitle("")
middenbeemster_points

```

```{r}
strep_plots_mid <- middenbeemster_clades / middenbeemster_strep_prop / middenbeemster_points +
  plot_layout(heights = c(1,1,1))

strep_plots_mid

# ggsave("./06-publication/main_figures/Figure_XX2/strep_props_middenbeemster.pdf", plot = strep_plots_mid, device = "pdf",
#        scale = 1, width = 4, height = 5, units = c("in"), dpi = 300)

```

## Canonical Correlation Analysis

```{r}
# load the Middenbeemster metadata file
# downlaod from github first into 00-documentation
# wget https://raw.githubusercontent.com/ivelsko/smoking_calculus/main/05-results.backup/Metadata_tables.RData
load("./00-documentation/Metadata_tables.RData")

```

```{r}

strep_gtdb <- anc_calc_strep_sp %>%
  # remove poorly-preserved samples
  select(-matches(poor_samples %>% str_c(collapse = "|"))) %>%
  # select only Velsko2022
  column_to_rownames("Species") %>%
  select(matches(lib_metadata %>% filter(Study == "Velsko2022") %>% pull(Sample_alias))) %>%
  # remove non-MID samples
  select(-matches("CMB|ELR|IVE")) %>%
  rownames_to_column("Species") %>%
  filter(str_detect(Species, "Streptococcus")) %>%
  # join with the Strep grup table for plotting
  inner_join(., gtdb_clades) %>%
  select(Species, Clade, everything()) %>%
  # convert to long-format
  pivot_longer(!Species:Clade, names_to = "Library_ID", values_to = "Counts") %>%
  dplyr::group_by(Library_ID, Clade) %>%
  summarize(Count_sum = sum(Counts)) %>%
  ungroup() %>%
  group_by(Library_ID) %>%
  mutate(Percent = Count_sum / sum(Count_sum)) %>%
  select(Library_ID, Clade, Percent) %>%
  pivot_wider(names_from = Clade, values_from = Percent)

```


```{r pca_species_all}


mid_table <- anc_calc_strep_sp %>%
  # remove poorly-preserved samples
  select(-matches(poor_samples %>% str_c(collapse = "|"))) %>%
  # select only Velsko2022
  column_to_rownames("Species") %>%
  select(matches(lib_metadata %>% filter(Study == "Velsko2022") %>% pull(Sample_alias))) %>%
  rownames_to_column("Species") %>%
  # remove CMB for AHC figure
  select(-matches("CMB|ELR|IVE")) %>%
  # these samples have no metadata
  select(-c("MID025.A0101","MID033.A0101","MID052.A0101","MID056.A0101","MID065.A0101","MID068.A0101","MID076.A0101","MID078.A0101")) %>%
  pivot_longer(!Species, names_to = "Library_ID",values_to = "Counts") %>%
  mutate(Counts = Counts +1) %>%
  spread(Species,Counts) %>%
  column_to_rownames("Library_ID")

# combine metadata
comb_metadata <- full_metadata %>%
  mutate(`DNA_molecules_per_library_x10^6_log` = log10(`DNA_molecules_per_library_x10^6`)) %>%
  full_join(., strep_gtdb, by = "Library_ID")


# prepare to run a PCA
# check the number of components to retain by tuning the PCA
mixOmics::tune.pca(mid_table, logratio = 'CLR')

pca.list <- mixOmics::pca(mid_table, ncomp = 5, logratio = 'CLR')

exp_var_all <- paste0(round(pca.list$prop_expl_var$X * 100, 2), "%")
all_pca_values <- pca.list$variates$X %>%
  as.data.frame() %>%
  rownames_to_column("Library_ID") %>%
  inner_join(comb_metadata, by = "Library_ID") %>%
  # inner_join(., strep_gtdb) %>%
  drop_na(Site_code) %>%
  mutate(Time_period_n = ifelse(Time_period == "Medieval",0,
                                ifelse(Time_period == "Industrial",1,2))) %>%
  mutate(Sex_n = ifelse(Sex == "Female", 0,
                        ifelse(Sex == "Male", 1,2))) %>%
  mutate(Pipenotch_n = ifelse(Pipenotch == "Present",0,
                              ifelse(Pipenotch == "Absent",1,2))) %>%
  mutate(Age_n = ifelse(Age == "13-18",0,
                        ifelse(Age == "18-25",1,
                               ifelse(Age == "25-45",2,
                                      ifelse(Age == "45+",4,5))))) %>%
  mutate(Site_code_n = ifelse(Site_code == "MID",0,
                              ifelse(Site_code == "CMB",1,
                                     ifelse(Site_code == "RAD",2,
                                            ifelse(Site_code == "KIL",3,
                                                   ifelse(Site_code == "ELR",4,
                                                          ifelse(Site_code == "IVE",5,
                                                                 ifelse(Site_code == "JAE",6,7))))))))


```

```{r pca_plot_cont}
# plot to check the pattern is still there with the Kraken2/GTDBr202 table
mid_pca_sanguinis <- ggplot(all_pca_values, aes(PC1, PC2, fill = Sanguinis, shape = Time_period)) +
     geom_point(shape = 21, size = 3.5, stroke = 0.3) +
     scale_fill_viridis_c(option = "C") +
     # stat_ellipse() +
     theme_minimal(base_size = 14) +
     theme(text = element_text(size=14)) +
     theme(legend.title = element_blank(),
           legend.key.size = unit(2,"mm"),
           legend.text = element_text(size = 6)) + 
     xlab(paste("PC1 - ", exp_var_all[1])) +
     ylab(paste("PC2 - ", exp_var_all[2])) +
     theme(legend.position = "right")
mid_pca_sanguinis

mid_pca_anginosus <- ggplot(all_pca_values, aes(PC1, PC2, fill = Anginosus, shape = Time_period)) +
     geom_point(shape = 21, size = 3.5, stroke = 0.3) +
     scale_fill_viridis_c(option = "C") +
     # stat_ellipse() +
     theme_minimal(base_size = 14) +
     theme(text = element_text(size=14)) +
     theme(legend.title = element_blank(),
           legend.key.size = unit(2,"mm"),
           legend.text = element_text(size = 6)) + 
     xlab(paste("PC1 - ", exp_var_all[1])) +
     ylab(paste("PC2 - ", exp_var_all[2])) +
     theme(legend.position = "right")
mid_pca_anginosus

mid_pca_gc <- ggplot(all_pca_values, aes(PC1, PC2, fill = gc_avg, shape = Time_period)) +
     geom_point(shape = 21, size = 3.5, stroke = 0.3) +
     scale_fill_viridis_c(option = "C") +
     # stat_ellipse() +
     theme_minimal(base_size = 14) +
     theme(text = element_text(size=14)) +
     theme(legend.title = element_blank(),
           legend.key.size = unit(2,"mm"),
           legend.text = element_text(size = 6)) + 
     xlab(paste("PC1 - ", exp_var_all[1])) +
     ylab(paste("PC2 - ", exp_var_all[2])) +
     theme(legend.position = "right")
mid_pca_gc

```

```{r}

mid_pca_plots <- mid_pca_sanguinis / mid_pca_anginosus / mid_pca_gc

mid_pca_plots

# ggsave("./06-publication/supplemental_figures/Sup_fig_S12/mid_pca_plots.pdf", plot = mid_pca_plots, device = "pdf",
       # scale = 1, width = 8, height = 10, units = c("in"), dpi = 300)

```

```{r}

correlations_plot <- ggplot(all_pca_values, aes(PC1, gc_avg, fill = Sanguinis, size = Anginosus)) +
     geom_point(shape = 21, stroke = 0.3) +
     scale_fill_viridis_c(option = "C") +
     geom_smooth(method = glm, se = F, col = "black", linewidth = 0.7) +
     theme_minimal(base_size = 14) +
     theme(text = element_text(size=14)) +
     theme(legend.title = element_blank(),
           legend.key.size = unit(2,"mm"),
           legend.text = element_text(size = 6)) + 
     ggpubr::stat_regline_equation(label.y = 48, aes(label = ..rr.label..)) +
     theme(legend.position = "right") +
     xlab("PC1 loading") +
     ylab(" Mean GC (%)")

correlations_plot

ggsave("./06-publication/supplemental_figures/Sup_fig_S12/correlations_plot.pdf", plot = correlations_plot, device = "pdf",
scale = 1, width = 9, height = 5, units = c("in"), dpi = 300)


```


```{r all_corrs}
# rename variables to look nice in figures
all_pca_values_select <- all_pca_values %>%
  select(Library_ID, PC1, PC2, seq_len_avg, gc_avg, No_reads_total, Age_n, Sex_n, Pipenotch_n, Min_no_Pipe_notches, `%AMTL`, `%teeth_with_caries`, calc_sup_SI_score, Peridontal_affect_score, `%_positions_with_Periodontal`, Max_Perio_Score, Calculus_extracted_mg, `extract_conc_ng/mg`, `extract_conc_ng/uL`, `extract_conc_after_storage_ng/uL`, `DNA_molecules_per_library_x10^6`,Calc_sub_SI_score, `%teeth_with_calc`, `%_positions_perioapical`, Sanguinis, Anginosus) %>%
  rename(`Seq length` = seq_len_avg,
         GC = gc_avg,
         `Total reads` = No_reads_total,
         Age = Age_n,
         Sex = Sex_n,
         Pipenotch = Pipenotch_n,
         `Min no. pipenotch` = Min_no_Pipe_notches,
         `% AMTL` = `%AMTL`,
         `% Caries` = `%teeth_with_caries`,
         `Supra calc score` = calc_sup_SI_score,
         `Perio score` = Peridontal_affect_score,
         `% Perio` = `%_positions_with_Periodontal`,
         `Max perio score` = Max_Perio_Score,
         `Extracted weight (mg)` = Calculus_extracted_mg,
         `Pre-storage [extract] (ng/mg)` = `extract_conc_ng/mg`,
         `Pre-storage [extract] (ng/uL)` = `extract_conc_ng/uL`,
         `Post-storage [extract] (ng/uL)` = `extract_conc_after_storage_ng/uL`,
         `[Library] (molecules)` = `DNA_molecules_per_library_x10^6`,
         `Sub calc score` = Calc_sub_SI_score,
         `% Calculus` = `%teeth_with_calc`,
         `% Perioapical` = `%_positions_perioapical`) %>%
  # re-order the columns
  select(Library_ID, Age, Sex, Pipenotch, `Min no. pipenotch`, `% AMTL`, `% Caries`, `Supra calc score`, `Sub calc score`, `% Calculus`, `Perio score`, `% Perio`, `Max perio score`, `% Perioapical`, `Extracted weight (mg)`, `Pre-storage [extract] (ng/mg)`, `Pre-storage [extract] (ng/uL)`, `Post-storage [extract] (ng/uL)`, `[Library] (molecules)`, `Seq length`, GC, `Total reads`, PC1, PC2, Sanguinis, Anginosus)

# select variables
form <- ~ Age + Sex + Pipenotch + `Min no. pipenotch` + `% AMTL` + `% Caries` + `Supra calc score` + `Sub calc score` + `% Calculus` + `Perio score` + `% Perio` + `Max perio score` + `% Perioapical` + `Extracted weight (mg)` + `Pre-storage [extract] (ng/mg)` + `Pre-storage [extract] (ng/uL)` + `Post-storage [extract] (ng/uL)` + `[Library] (molecules)` + `Seq length` + GC + `Total reads` + PC1 + PC2 + Sanguinis + Anginosus

# compute CCA
C_all = canCorPairs(form, all_pca_values_select)
plotCorrMatrix( C_all )


```


```{r pearson_corr_mid}
# test for significant differences in diversity between the metadata categories

pearson_all <- all_pca_values_select %>%
rstatix::cor_test(., Age, Sex, Pipenotch, `Min no. pipenotch`, `% AMTL`, `% Caries`, `Supra calc score`, `Sub calc score`, `% Calculus`, `Perio score`, `% Perio`, `Max perio score`, `% Perioapical`, `Extracted weight (mg)`, `Pre-storage [extract] (ng/mg)`, `Pre-storage [extract] (ng/uL)`, `Post-storage [extract] (ng/uL)`, `[Library] (molecules)`, `Seq length`, GC, `Total reads`, PC1, PC2, Sanguinis, Anginosus, method="pearson")

pearson_all

pearson_all %>%
  mutate(same = var1 == var2) %>%
  filter(same == FALSE) %>%
  select(-same) %>%
  filter(p <= 0.001) %>%
  filter(cor > 0.40 | cor < -0.40) %>%
  distinct(statistic, .keep_all = TRUE)
  
pearson_all %>%
  mutate(same = var1 == var2) %>%
  filter(same == FALSE) %>%
  select(-same) %>%
  filter(var1 == "Anginosus") %>%
  arrange(desc(cor)) %>%
  filter(p <= 0.001) %>%
  filter(cor > 0.40 | cor < -0.40) %>%
  distinct(statistic, .keep_all = TRUE)


```

```{r}

C_all %>%
  as_data_frame(.) %>%
  mutate(names = rownames(C_all)) %>%
  select(names, everything()) %>%
  pivot_longer(!names, names_to = "Corrs", values_to = "values") %>%
  filter(values != 1) %>%
  filter(values >= 0.4) %>%
  distinct(values, .keep_all = TRUE)


C_all %>%
  as_data_frame(.) %>%
  mutate(names = rownames(C_all)) %>%
  select(names, everything()) %>%
  pivot_longer(!names, names_to = "Corrs", values_to = "values") %>%
  filter(names == "GC") %>%
  arrange(desc(values))

C_all %>%
  as_data_frame(.) %>%
  mutate(names = rownames(C_all)) %>%
  select(names, everything()) %>%
  pivot_longer(!names, names_to = "Corrs", values_to = "values") %>%
  filter(str_detect(names, "Anginosus|Sanguinis")) %>%
  arrange(names, desc(values))

```


```{r}
# colorset <- rev(colorspace::sequential_hcl(10, palette = "BuPu"))

colorset <- c("#ffffff","#e8e2ee","#d1c6dc","#baaacb","#a48fba","#8d74aa","#775b99","#604289","#492978","#311068")

 pvals_all <- all_pca_values_select %>%
  column_to_rownames("Library_ID") %>%
  as.matrix(.) %>%
  corrplot::cor.mtest(., method="pearson")

C_all %>%
  corrplot::corrplot(., p.mat = pvals_all$p, order = "original", type = "upper", col = colorset, is.corr = FALSE, cl.cex = 0.7, diag = FALSE, tl.cex = 0.7,
                     tl.col = 'black', sig.level = c(0.001), pch.cex = 0.7, insig = 'label_sig', pch.col = 'grey20')

```

```{r, eval = F}
svg(file = "./06-publication/main_figures/Figure_2/mid_corr_plot.svg") 

C_all %>%
  corrplot::corrplot(., p.mat = pvals_all$p, order = "original", type = "upper", col = colorset, is.corr = FALSE, cl.cex = 0.7, diag = FALSE, tl.cex = 0.7,
                     tl.col = 'black', sig.level = c(0.001), pch.cex = 0.7, insig = 'label_sig', pch.col = 'grey20')

dev.off()

```

















