---
title: "Ancient calculus Strep clade distributions"
author: "Irina Velsko"
date: "`r format(Sys.time(), '%b %d, %Y')`"
output:
    github_document:
        fig_width: 8
        fig_height: 6
        toc: true
---

```{r load_libraries, echo = F, message = F}
library(knitr)
library(data.table)
library(janitor)
library(tidyverse)
library(patchwork)
opts_chunk$set(echo=F, warning=F, message=F, dpi=150)
```

Set the working directory of the notebook to the parent directory of the 
notebook itself.  

```{r setup}
knitr::opts_knit$set(root.dir = normalizePath("../../.."))
```


```{r}
# file with species names and clade designations
gtdb_clades <- fread("./00-documentation/dRep_gtdb_clades.tsv")

gtdb_clades <- gtdb_clades %>%
  mutate(Clade = fct_relevel(Clade, "Sanguinis","Mitis","Salivarius","Anginosus","Bovis","Pyogenic","Mutans","Downei","Other","Unknown"))

```


```{r metadata}

# get only industrial saliva from the metadata table
lib_metadata <- fread("./00-documentation/strep_clades_metadata.tsv") %>%
  filter(str_detect(Sample_group, "ancient_calculus")) %>%
  distinct()

```


```{r}
# set colors to resemble James' figure

clade_colors <- c("Sanguinis" = "#a50026",
                  "Mitis" = "#d73027",
                  "Salivarius" = "#f46d43",
                  "Anginosus" = "#fee090",
                  "Bovis" = "#abd9e9",
                  "Pyogenic" = "#74add1",
                  "Mutans" = "#4575b4",
                  "Downei" = "#313695",
                  "Other" = "#4d4d4d",
                  "Unknown" = "#e0e0e0")

genus_colors <- c("Streptococcus" = "#a50026", "Other" = "#e0e0e0")

```


## Kraken2 GTDB r202 table
```{r load_data}
# read in the species table. It has the column names already
anc_calc_raw <- fread("./05-results/anc_calc.kraken2.gtdb.report_mpa.tsv.gz") 

anc_names <- fread("./05-results/anc_calc_names.tsv", header = F)  %>%
  rename(Library_ID = 1) %>%
  mutate(Library_ID = str_replace_all(Library_ID, ".SG1.1", ""),
         Library_ID = str_replace_all(Library_ID, ".SG1", ""))

# filter to have only species and remove all species with <1000 reads assigned
# even filtering out taxa with <10000 counts doesn't help
anc_calc_strep_sp <- anc_calc_raw %>% 
  filter(str_detect(Lineage, "s__s__")) %>%
  separate(Lineage, into = c("domain","phylum","class","order","family","genus","Species"), sep = "\\|", extra = "merge") %>%
  select(-c("domain","phylum","class","order","family","genus")) %>%
  mutate(Species = str_replace_all(Species, "s__s__","")) %>%
  filter(str_detect(Species, "Streptococcus")) %>%
  # remove Radcliffe soil and dentin
  select(-matches("CSS|CSD"))

```

Read in poorly-preserved samples. 
```{r cuperdec_poor}
# read in table of poorly-preserved samples as determined by cuperdec
poor_samples <- fread("./05-results/cuperdec_anc_calc_poor_samples.tsv") %>%
  pull(Sample)

poor_df <- fread("./05-results/cuperdec_anc_calc_poor_samples.tsv") %>%
  mutate(Preservation = "Poor") %>%
  rename(Library_ID = Sample)

```

### All samples
```{r strep_clade_props}

# set the order of samples based on proportion of Sanguinis and agninosis
# need to get the proportion of each for this
# then arrange by proportion

sample_order_rs <- anc_calc_strep_sp  %>%
  # remove poorly-preserved samples
  select(-matches(poor_samples %>% str_c(collapse = "|"))) %>%
  # join with the Strep grup table for plotting
  inner_join(., gtdb_clades) %>%
  select(-Species) %>%
  select(Clade, everything()) %>%
  # long-format
  gather("Library_ID","Counts", 2:ncol(.)) %>%
  # sum together all species per group
  group_by(Library_ID, Clade) %>%
  summarize(Reads = sum(Counts)) %>%
  # transpose
  spread(Clade, Reads) %>%
  # convert table to proportions
  adorn_percentages(denominator = "row") %>%
  # full_join(., poor_samples %>% as_tibble(.) %>% rename(Library_ID = 1) %>% mutate(Preservation = "Poor")) %>%
  # mutate(Preservation = ifelse(is.na(Preservation), "Good",Preservation)) %>%
  # arrange by Sanguinis and for the ones w/o Sanguinis, by Anginosus
  # arrange(Preservation, Library_ID)
  arrange(desc(Sanguinis), Anginosus) %>% # Preservation, 
  pull(Library_ID)


ac_clades <- anc_calc_strep_sp %>%
  # remove poorly-preserved samples
  select(-matches(poor_samples %>% str_c(collapse = "|"))) %>%
  # filter(str_detect(Species, "Streptococcus")) %>%
  # join with the Strep grup table for plotting
  inner_join(., gtdb_clades) %>%
  select(Species, Clade, everything()) %>%
  # convert to long-format
  pivot_longer(!Species:Clade, names_to = "Library_ID", values_to = "Counts") %>%
  mutate(Library_ID = fct_relevel(Library_ID, sample_order_rs)) %>%
  dplyr::group_by(Library_ID, Clade) %>%
  summarize(Count_sum = sum(Counts)) %>%
  ggplot(., aes(x = Library_ID, y = Count_sum, fill = Clade)) +
         geom_bar(position = "fill", stat = "identity") + # , color = "black"
         theme_minimal(base_size = 10) +
         scale_fill_manual(values = clade_colors) +
         theme(axis.text.x = element_blank(),
               axis.text.y = element_text(size = 14),
               panel.grid.major.x = element_blank()) +
         # theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5),
         #       axis.text = element_text(size = 8)) +
         # scale_y_continuous(breaks=scales::pretty_breaks(n=6)) +
         # geom_hline(yintercept = 0.5, linetype = "dotted") +
         scale_y_continuous(labels = function(x) paste0(x*100)) + # Multiply by 100
         ylab("Percent") +
         labs(fill = "Clade") +
         xlab("")
ac_clades

```


```{r save_rs_order, eval = F}

# sample_order_rs %>%
#   as.data.frame(.) %>%
#  rename(Library_ID = ".") %>%
# fwrite(., "./05-results.backup/malt_rs_Strep_group_order.tsv", sep = "\t", quote = F)

```


```{r rs_strep_proportion}

strep_prop <- anc_calc_raw %>% 
  # remove poorly-preserved samples
  select(-matches(poor_samples %>% str_c(collapse = "|"))) %>%
  filter(str_detect(Lineage, "s__s__")) %>%
  separate(Lineage, into = c("domain","phylum","class","order","family","genus","Species"), sep = "\\|", extra = "merge") %>%
  select(-c("domain","phylum","class","order","family","genus")) %>%
  mutate(Species = str_replace_all(Species, "s__s__","")) %>%
  # make a column with Strep or other
  mutate(Genus = ifelse(str_detect(Species,"Streptococcus"),"Streptococcus","Other")) %>%
  # remove Species column leaving Genus column
  select(Genus, everything()) %>%
  select(-Species) %>%
  # convert to long format
  gather("Library_ID","Counts", 2:ncol(.)) %>%
  group_by(Library_ID, Genus) %>%
  # sum all Strep read counts and all Other read counts
  summarize(Reads = sum(Counts)) %>%
  spread(Genus, Reads) %>%
  # convert to proportions
  adorn_percentages() %>%
  ungroup()

ac_strep_prop <- strep_prop %>%
  gather("Genus","Counts", 2:ncol(.)) %>%
  mutate(Library_ID = fct_relevel(Library_ID, sample_order_rs)) %>%
  arrange(Library_ID) %>%
  ggplot(., aes(x = Library_ID, y = Counts, fill = Genus)) +
         geom_bar(stat = "identity") + # , color = "black"
         theme_minimal(base_size = 10) +
         scale_fill_manual(values = genus_colors) +
         theme(axis.text.x = element_blank(),
               axis.text.y = element_text(size = 14),
               panel.grid.major.x = element_blank()) +
         # theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5),
         #       axis.text = element_text(size = 8)) +
         # scale_y_continuous(breaks=scales::pretty_breaks(n=6)) +
         scale_y_continuous(labels = function(x) paste0(x*100)) + # Multiply by 100
         ylab("Percent") +
         xlab("")
ac_strep_prop

```

```{r}

strep_prop %>%
  mutate(Library_ID = fct_relevel(Library_ID, sample_order_rs)) %>%
  arrange(Library_ID)
  

```


```{r sanguinis_anginosus}

aardvark <- anc_calc_raw %>% 
  # remove poorly-preserved samples
  select(-matches(poor_samples %>% str_c(collapse = "|"))) %>%
  filter(str_detect(Lineage, "s__s__")) %>%
  separate(Lineage, into = c("domain","phylum","class","order","family","genus","Species"), sep = "\\|", extra = "merge") %>%
  select(-c("domain","phylum","class","order","family","genus")) %>%
  mutate(Species = str_replace_all(Species, "s__s__","")) %>%
  # make a column with Strep or other
  mutate(Genus_inc = ifelse(str_detect(Species,"Streptococcus"),"Streptococcus", "NonStrep")) %>%
  left_join(., gtdb_clades , by = "Species") %>%
  # remove Species column leaving Genus column
  mutate(Genus = replace_na(as.character(Clade), "NonStrep")) %>%
  select(Genus, everything()) %>%
  select(-matches("Species|Clade|Genus_inc")) %>%
  # convert to long format
  gather("Library_ID","Counts", 2:ncol(.)) %>%
  group_by(Library_ID, Genus) %>%
  # sum all Strep read counts and all Other read counts
  summarize(Reads = sum(Counts)) %>%
  spread(Genus, Reads) %>%
  # convert to proportions
  adorn_percentages() %>%
  ungroup() %>%
  # rearrange column order
  select(Library_ID, NonStrep, Sanguinis, Anginosus, everything()) %>%
  # now sum counts for columns we're not interested in 
  mutate(OtherStrep = select(., Bovis:Salivarius) %>% rowSums()) %>%
  # rearrange column order again and drop the unwanted columns
  select(Library_ID, NonStrep, Sanguinis, Anginosus) %>%
  pivot_longer(!Library_ID, names_to = "Genus", values_to = "Counts") %>%
  # order the Library ID by 
  mutate(Library_ID = fct_relevel(Library_ID, sample_order_rs),
         Counts = Counts + 0.0001) %>%
         # Genus = fct_relevel(Genus, "NonStrep","OtherStrep","Sanguinis","Anginosus")) %>%
  filter(str_detect(Genus, "Sanguinis|Anginosus"))  %>%
  filter(Genus != "OtherStrep")

ac_points <- aardvark %>%
  arrange(Library_ID) %>%
  mutate(Percent = Counts * 100) %>%
  mutate(Library_ID = fct_drop(Library_ID)) %>%
  ggplot(., aes(x = Library_ID, y = Percent, shape = Genus, color = Genus)) +
         geom_point(size = 2.5) + 
         theme_minimal(base_size = 10) +
         scale_color_manual(values = clade_colors) + # c("#fee090","#a50026")
         scale_shape_manual(values = c(16,18,17)) +
         theme(
               axis.text.x = element_blank(),
               axis.text.y = element_text(size = 14),
               panel.grid.major.x = element_blank()
               # axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5),
               # axis.text = element_text(size = 14)
               ) +
         scale_y_log10() +
         # labs(fill = "Clade", shape = "Clade") +
         ylab("Percent") +
         xlab("Sample")

ac_points

```

```{r}
# number/percent of samples with Anginosus over 50% of Strep
# there are 71 samples with Anginosus over 50% of Strep, and 483 samples (14.7%)
anc_calc_strep_sp %>%
  # remove poorly-preserved samples
  select(-matches(poor_samples %>% str_c(collapse = "|"))) %>%
  # filter(str_detect(Species, "Streptococcus")) %>%
  # join with the Strep grup table for plotting
  inner_join(., gtdb_clades) %>%
  select(Species, Clade, everything()) %>%
  # convert to long-format
  pivot_longer(!Species:Clade, names_to = "Library_ID", values_to = "Counts") %>%
  mutate(Library_ID = fct_relevel(Library_ID, sample_order_rs)) %>%
  dplyr::group_by(Library_ID, Clade) %>%
  summarize(Count_sum = sum(Counts)) %>%
  pivot_wider(names_from = "Library_ID", values_from = "Count_sum") %>%
  adorn_percentages(denominator = "col") %>%
  as_tibble() %>%
  pivot_longer(!Clade, names_to = "Library_ID", values_to = "Proportion") %>%
  filter(Clade == "Anginosus", Proportion >= 0.5) %>%
  arrange(Library_ID)


strep_plots <- ac_clades / ac_strep_prop / ac_points +
  plot_layout(heights = c(1,1,1))

strep_plots

# ggsave("./06-publication/main_figures/Figure_1/strep_props_ac.pdf", plot = strep_plots, device = "pdf",
#        scale = 1, width = 14, height = 9, units = c("in"), dpi = 300)

```

```{r}
anc_calc_strep_sp %>%
  # remove poorly-preserved samples
  select(-matches(poor_samples %>% str_c(collapse = "|"))) %>%
  # filter(str_detect(Species, "Streptococcus")) %>%
  # join with the Strep grup table for plotting
  inner_join(., gtdb_clades) %>%
  select(Species, Clade, everything()) %>%
  # convert to long-format
  pivot_longer(!Species:Clade, names_to = "Library_ID", values_to = "Counts") %>%
  mutate(Library_ID = fct_relevel(Library_ID, sample_order_rs)) %>%
  dplyr::group_by(Library_ID, Clade) %>%
  summarize(Count_sum = sum(Counts)) %>%
  ungroup() %>%
  group_by(Library_ID) %>%
  mutate(Percent = Count_sum / sum(Count_sum) * 100) %>%
  ungroup() %>%
  select(Library_ID, Clade, Percent) %>%
  pivot_wider(names_from = "Clade", values_from = "Percent") %>%
  full_join(., strep_prop %>%
            mutate(Library_ID = fct_relevel(Library_ID, sample_order_rs)) %>%
            arrange(Library_ID) %>%
              rename(Genus_other = Other)) %>%
  full_join(., aardvark %>%
    pivot_wider(names_from = "Genus", values_from = "Counts") %>%
      rename(Sanguinis_tot = Sanguinis,
             Anginosus_tot = Anginosus)) 
# %>%
#   fwrite(., "./06-publication/supplemental_tables/sup_table_anc_strep_clades_pct.tsv", quote = F, sep = "\t")

```

```{r}
anc_calc_strep_sp %>%
  # remove poorly-preserved samples
  select(-matches(poor_samples %>% str_c(collapse = "|"))) %>%
  # filter(str_detect(Species, "Streptococcus")) %>%
  # join with the Strep grup table for plotting
  inner_join(., gtdb_clades) %>%
  select(Species, Clade, everything()) %>%
  # convert to long-format
  pivot_longer(!Species:Clade, names_to = "Library_ID", values_to = "Counts") %>%
  mutate(Library_ID = fct_relevel(Library_ID, sample_order_rs)) %>%
  dplyr::group_by(Library_ID, Clade) %>%
  summarize(Count_sum = sum(Counts)) %>%
  ungroup() %>%
  group_by(Library_ID) %>%
  mutate(Percent = Count_sum / sum(Count_sum) * 100) %>%
  ungroup() %>%
  select(Library_ID, Clade, Percent) %>%
  group_by(Library_ID) %>%
  slice_max(Percent) %>%
  ungroup() %>%
  group_by(Clade) %>%
  count() %>%
  ungroup()
  

anc_calc_strep_sp %>%
  # remove poorly-preserved samples
  select(-matches(poor_samples %>% str_c(collapse = "|"))) %>%
  # filter(str_detect(Species, "Streptococcus")) %>%
  # join with the Strep grup table for plotting
  inner_join(., gtdb_clades) %>%
  select(Species, Clade, everything()) %>%
  # convert to long-format
  pivot_longer(!Species:Clade, names_to = "Library_ID", values_to = "Counts") %>%
  mutate(Library_ID = fct_relevel(Library_ID, sample_order_rs)) %>%
  dplyr::group_by(Library_ID, Clade) %>%
  summarize(Count_sum = sum(Counts)) %>%
  ungroup() %>%
  group_by(Library_ID) %>%
  mutate(Percent = Count_sum / sum(Count_sum) * 100) %>%
  ungroup() %>%
  select(Library_ID, Clade, Percent) %>%
  group_by(Library_ID) %>%
  slice_max(Percent) %>%
  ungroup() 
# %>%
#   fwrite(., "./05-results/anc_calc_dominant_clade_per_library.tsv", sep = "\t", quote = F)

```














